<?php
/**
* Author:
* Michael Kefeder
*/

$labels = array();
$labels['label'] = 'Thunderbird Labels';
$labels['label0'] = 'No Label';
$labels['label1'] = 'Important';
$labels['label2'] = 'Work';
$labels['label3'] = 'Personal';
$labels['label4'] = 'To do';
$labels['label5'] = 'Later';

$labels['tb_label_options'] = 'Thunderbird Labels Options';
$labels['tb_label_enable_option'] = 'Enable labels';
$labels['tb_label_enable_shortcuts_option'] = 'Enable keyboard shortcuts';
$labels['tb_label_button_label'] = 'Labels';
$labels['tb_label_button_title'] = 'Set labels on messages';
$labels['tb_label_contextmenu_title'] = 'Labels';
$labels['tb_label_style_option'] = "UI Style for labels";
$labels['tb_label_label'] = "Label";

$labels['labels_title'] = 'Labels';
$labels['add_label'] = 'Create new label';
$labels['create_label'] = 'Create';
$labels['cancel'] = 'Cancel';
$labels['label_name'] = 'Label name';
$labels['label_name_placeholder'] = 'Please enter a new label name...';
$labels['label_color'] = 'Label color';
$labels['filter_by_label'] = 'Filtered by label';
$labels['clear_filter'] = 'Clear filter';
$labels['delete_label'] = 'Delete label';
$labels['rename_label'] = 'Rename label';
$labels['change_color'] = 'Change label color';
$labels['confirm_delete_label'] = 'Are you sure you want to delete this label?';

$messages = array();

