<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'دروب بوكس';
$labels['xgoogle_drive_name'] = 'جوجل درايف';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'إدراج رابط للرسالة';
$labels['download_and_attach'] = 'تنزيل وإرفاق';
$labels['sidebar'] = 'الشريط الجانبي';
$labels['sidebar_items'] = 'عناصر الشريط الجانبي';
$labels['sidebar_change_order'] = 'اسحب عناصر الشريط الجانبي وأفلتها لتغيير ترتيبها.';
$labels['preview'] = 'معاينة';
$labels['apps'] = 'التطبيقات';
$labels['sidebar'] = 'الشريط الجانبي';
$labels['hide'] = 'إخفاء';
$labels['invalid_image_extension'] = 'امتداد ملف صورة غير صالح. الامتدادات المسموح بها هي: $ext.';
$labels['invalid_image_format'] = 'هذا الملف ليس صورة صالحة.';
$labels['copy_to_clipboard'] = 'نسخ إلى الحافظة';
$labels['copied_to_clipboard'] = 'تم النسخ إلى الحافظة.';
$labels['cannot_copy_to_clipboard'] = 'لا يمكن نسخ النص إلى الحافظة.';
