<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Εισαγωγή συνδέσμου στο μήνυμα';
$labels['download_and_attach'] = 'Κατεβάστε και επισυνάψτε';
$labels['sidebar'] = 'Πλαϊνή μπάρα';
$labels['sidebar_items'] = 'Στοιχεία πλευρικής μπάρας';
$labels['sidebar_change_order'] = 'Σύρετε και αποθέστε στοιχεία της πλευρικής γραμμής για να αλλάξετε τη σειρά τους.';
$labels['preview'] = 'Προεπισκόπηση';
$labels['apps'] = 'Εφαρμογές';
$labels['sidebar'] = 'Πλαϊνή μπάρα';
$labels['hide'] = 'Απόκρυψη';
$labels['invalid_image_extension'] = 'Μη έγκυρη επέκταση αρχείου εικόνας. Οι επιτρεπόμενες επεκτάσεις είναι: $ext.';
$labels['invalid_image_format'] = 'Αυτό το αρχείο δεν είναι έγκυρη εικόνα.';
$labels['copy_to_clipboard'] = 'Αντιγραφή στο πρόχειρο';
$labels['copied_to_clipboard'] = 'Αντιγραφή στο πρόχειρο.';
$labels['cannot_copy_to_clipboard'] = 'Δεν είναι δυνατή η αντιγραφή κειμένου στο πρόχειρο.';
