<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Sisesta link sõnumile';
$labels['download_and_attach'] = 'Laadige alla ja kinnitage';
$labels['sidebar'] = 'Külgriba';
$labels['sidebar_items'] = 'Külgriba elemendid';
$labels['sidebar_change_order'] = 'Lohistage küljeriba elemente, et muuta nende järjekorda.';
$labels['preview'] = 'Eelvaade';
$labels['apps'] = 'Rakendused';
$labels['sidebar'] = 'Külgriba';
$labels['hide'] = 'Peida';
$labels['invalid_image_extension'] = 'Pildifaili laiend on vale. Lubatud laiendused on järgmised: $ext.';
$labels['invalid_image_format'] = 'See fail ei ole kehtiv pilt.';
$labels['copy_to_clipboard'] = 'Kopeeri lõikelauale';
$labels['copied_to_clipboard'] = 'Kopeeritud lõikelauale.';
$labels['cannot_copy_to_clipboard'] = 'Ei saa kopeerida teksti lõikelauale.';
