<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Link beillesztése az üzenethez';
$labels['download_and_attach'] = 'Letöltés és csatolás';
$labels['sidebar'] = 'Oldalsáv';
$labels['sidebar_items'] = 'Oldalsáv elemek';
$labels['sidebar_change_order'] = 'Az oldalsáv elemeinek sorrendjének megváltoztatásához húzza az elemeket.';
$labels['preview'] = 'Előnézet';
$labels['apps'] = 'Alkalmazások';
$labels['sidebar'] = 'Oldalsáv';
$labels['hide'] = 'Rejtsd el';
$labels['invalid_image_extension'] = 'Érvénytelen képfájl kiterjesztés. Az engedélyezett kiterjesztések a következők: $ext.';
$labels['invalid_image_format'] = 'Ez a fájl nem érvényes kép.';
$labels['copy_to_clipboard'] = 'Másolás a vágólapra';
$labels['copied_to_clipboard'] = 'A vágólapra másolva.';
$labels['cannot_copy_to_clipboard'] = 'Nem lehet szöveget másolni a vágólapra.';
