<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Menyisipkan tautan ke pesan';
$labels['download_and_attach'] = 'Unduh dan lampirkan';
$labels['sidebar'] = 'Bilah samping';
$labels['sidebar_items'] = 'Item bilah sisi';
$labels['sidebar_change_order'] = 'Seret dan jatuhkan item bilah samping untuk mengubah urutannya.';
$labels['preview'] = 'Pratinjau';
$labels['apps'] = 'Aplikasi';
$labels['sidebar'] = 'Bilah samping';
$labels['hide'] = 'Sembunyikan';
$labels['invalid_image_extension'] = 'Ekstensi file gambar tidak valid. Ekstensi yang diizinkan adalah: $ext.';
$labels['invalid_image_format'] = 'File ini bukan gambar yang valid.';
$labels['copy_to_clipboard'] = 'Salin ke papan klip';
$labels['copied_to_clipboard'] = 'Disalin ke papan klip.';
$labels['cannot_copy_to_clipboard'] = 'Tidak dapat menyalin teks ke papan klip.';
