<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Inserisci collegamento al messaggio';
$labels['download_and_attach'] = 'Scarica e allega';
$labels['sidebar'] = 'Barra laterale';
$labels['sidebar_items'] = 'Elementi della barra laterale';
$labels['sidebar_change_order'] = 'Trascina gli elementi della barra laterale per cambiarne l\'ordine.';
$labels['preview'] = 'Anteprima';
$labels['apps'] = 'Applicazioni';
$labels['sidebar'] = 'Barra laterale';
$labels['hide'] = 'Nascondi';
$labels['invalid_image_extension'] = 'Estensione file immagine non valida. Le estensioni consentite sono: $ext.';
$labels['invalid_image_format'] = 'Questo file non è un\'immagine valida.';
$labels['copy_to_clipboard'] = 'Copia negli appunti';
$labels['copied_to_clipboard'] = 'Copiato negli appunti.';
$labels['cannot_copy_to_clipboard'] = 'Impossibile copiare il testo negli appunti.';
