<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'ドロップボックス';
$labels['xgoogle_drive_name'] = 'グーグルドライブ';
$labels['xwebdav_name'] = 'ウェブダブリュー';
$labels['insert_link'] = 'メッセージへのリンクを挿入';
$labels['download_and_attach'] = 'ダウンロードして添付する';
$labels['sidebar'] = 'サイドバー';
$labels['sidebar_items'] = 'サイドバー項目';
$labels['sidebar_change_order'] = 'サイドバーアイテムをドラッグ＆ドロップして並び順を変更できます。';
$labels['preview'] = 'プレビュー';
$labels['apps'] = 'アプリ';
$labels['sidebar'] = 'サイドバー';
$labels['hide'] = '隠す';
$labels['invalid_image_extension'] = '画像ファイルの拡張子が無効です。許可される拡張子は次の拡張子です。';
$labels['invalid_image_format'] = 'このファイルは有効な画像ではありません。';
$labels['copy_to_clipboard'] = 'クリップボードにコピー';
$labels['copied_to_clipboard'] = 'クリップボードにコピー。';
$labels['cannot_copy_to_clipboard'] = 'テキストをクリップボードにコピーできない。';
