<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google 드라이브';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = '메시지 링크 삽입';
$labels['download_and_attach'] = '다운로드 및 첨부';
$labels['sidebar'] = '사이드바';
$labels['sidebar_items'] = '사이드바 항목';
$labels['sidebar_change_order'] = '사이드바 항목을 끌어다 놓아 순서를 변경할 수 있습니다.';
$labels['preview'] = '미리 보기';
$labels['apps'] = '앱';
$labels['sidebar'] = '사이드바';
$labels['hide'] = '숨기기';
$labels['invalid_image_extension'] = '잘못된 이미지 파일 확장자입니다. 허용되는 확장자는 다음과 같습니다: ext.';
$labels['invalid_image_format'] = '이 파일은 유효한 이미지가 아닙니다.';
$labels['copy_to_clipboard'] = '클립보드에 복사';
$labels['copied_to_clipboard'] = '클립보드에 복사했습니다.';
$labels['cannot_copy_to_clipboard'] = '텍스트를 클립보드에 복사할 수 없습니다.';
