<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = '"Dropbox"';
$labels['xgoogle_drive_name'] = '"Google" diskas';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Įterpti nuorodą į pranešimą';
$labels['download_and_attach'] = 'Atsisiųsti ir pridėti';
$labels['sidebar'] = 'Šoninė juosta';
$labels['sidebar_items'] = 'Šoninės juostos elementai';
$labels['sidebar_change_order'] = 'Vilkite ir nuleiskite šoninės juostos elementus, kad pakeistumėte jų tvarką.';
$labels['preview'] = 'Peržiūra';
$labels['apps'] = 'Programėlės';
$labels['sidebar'] = 'Šoninė juosta';
$labels['hide'] = 'Paslėpti';
$labels['invalid_image_extension'] = 'Netinkamas vaizdo failo plėtinys. Leidžiami šie plėtiniai: Leidžiami: $ext.';
$labels['invalid_image_format'] = 'Šis failas nėra tinkamas atvaizdas.';
$labels['copy_to_clipboard'] = 'Kopijuoti į iškarpinę';
$labels['copied_to_clipboard'] = 'Nukopijuota į iškarpinę.';
$labels['cannot_copy_to_clipboard'] = 'Negalima kopijuoti teksto į iškarpinę.';
