<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Link naar bericht invoegen';
$labels['download_and_attach'] = 'Downloaden en bijvoegen';
$labels['sidebar'] = 'Zijbalk';
$labels['sidebar_items'] = 'Items in de zijbalk';
$labels['sidebar_change_order'] = 'Sleep zijbalk-items om hun volgorde te veranderen.';
$labels['preview'] = 'Voorbeeld';
$labels['apps'] = 'Apps';
$labels['sidebar'] = 'Zijbalk';
$labels['hide'] = 'Verberg';
$labels['invalid_image_extension'] = 'Ongeldige bestandsextensie. De toegestane extensies zijn: $ext.';
$labels['invalid_image_format'] = 'Dit bestand is geen geldige afbeelding.';
$labels['copy_to_clipboard'] = 'Kopiëren naar klembord';
$labels['copied_to_clipboard'] = 'Gekopieerd naar klembord.';
$labels['cannot_copy_to_clipboard'] = 'Kan tekst niet naar klembord kopiëren.';
