<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Wpisz link do wiadomości';
$labels['download_and_attach'] = 'Pobierz i załącz';
$labels['sidebar'] = 'Pasek boczny';
$labels['sidebar_items'] = 'Obiekty na pasku bocznym';
$labels['sidebar_change_order'] = 'Przeciągnij i upuść obiekty na pasku bocznym, aby zmienić ich kolejność.';
$labels['preview'] = 'Podgląd';
$labels['apps'] = 'Aplikacje';
$labels['sidebar'] = 'Pasek boczny';
$labels['hide'] = 'Ukryj';
$labels['invalid_image_extension'] = 'Niewłaściwe rozszerzenie pliku obrazu. Dostępne rozszerzenia to: $ext.';
$labels['invalid_image_format'] = 'Ten plik nie jest obrazem.';
$labels['copy_to_clipboard'] = 'Kopiuj do schowka';
$labels['copied_to_clipboard'] = 'Skopiowano do schowka.';
$labels['cannot_copy_to_clipboard'] = 'Nie można skopiować tekstu do schowka.';
