<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Mesaja bağlantı ekle';
$labels['download_and_attach'] = 'İndirin ve ekleyin';
$labels['sidebar'] = 'Kenar Çubuğu';
$labels['sidebar_items'] = 'Kenar çubuğu öğeleri';
$labels['sidebar_change_order'] = 'Sıralarını değiştirmek için kenar çubuğu öğelerini sürükleyip bırakın.';
$labels['preview'] = 'Önizleme';
$labels['apps'] = 'Uygulamalar';
$labels['sidebar'] = 'Kenar Çubuğu';
$labels['hide'] = 'Gizle';
$labels['invalid_image_extension'] = 'Geçersiz görüntü dosyası uzantısı. İzin verilen uzantılar şunlardır: $ext.';
$labels['invalid_image_format'] = 'Bu dosya geçerli bir resim değil.';
$labels['copy_to_clipboard'] = 'Panoya kopyala';
$labels['copied_to_clipboard'] = 'Panoya kopyalandı.';
$labels['cannot_copy_to_clipboard'] = 'Metin panoya kopyalanamıyor.';
