<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Možnosti rozhraní';
$labels['disable_mobile_skin'] = 'Použití skinu na ploše';
$labels['enable_mobile_skin'] = 'Použití mobilní kůže';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Vzhled a pocit pokožky';
$labels['skin_look_and_feel'] = 'Vzhled a pocit pokožky';
$labels['icons'] = 'Ikony';
$labels['icons_solid'] = 'Solid';
$labels['icons_traditional'] = 'Tradiční';
$labels['icons_outlined'] = 'Načrtnuto';
$labels['icons_material'] = 'Materiál';
$labels['icons_cartoon'] = 'Kreslený film';
$labels['setting_list_icons'] = 'Ikony v seznamech';
$labels['setting_button_icons'] = 'Ikony na tlačítkách';
$labels['setting_font_size'] = 'Velikost písma';
$labels['font_size_xs'] = 'Nejmenší';
$labels['font_size_s'] = 'Menší';
$labels['font_size_n'] = 'Normální';
$labels['font_size_l'] = 'Větší';
$labels['font_size_xl'] = 'Největší';
$labels['setting_thick_font'] = 'Silné písmo';
$labels['setting_font_family'] = 'Rodina písma';
$labels['setting_color'] = 'Barva';
$labels['save_hint'] = 'Nezapomeňte uložit nastavení kliknutím na tlačítko "Uložit" níže.';

