<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Indstillinger for grænseflader';
$labels['disable_mobile_skin'] = 'Brug desktop skin';
$labels['enable_mobile_skin'] = 'Brug mobil hud';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Brugerfladens udseende';
$labels['skin_look_and_feel'] = 'Brugerfladens udseende';
$labels['icons'] = 'Ikoner';
$labels['icons_solid'] = 'Solid';
$labels['icons_traditional'] = 'Traditionel';
$labels['icons_outlined'] = 'Skitseret';
$labels['icons_material'] = 'Materiale';
$labels['icons_cartoon'] = 'Tegneserie';
$labels['setting_list_icons'] = 'Ikoner i lister';
$labels['setting_button_icons'] = 'Ikoner på knapper';
$labels['setting_font_size'] = 'Skriftstørrelse';
$labels['font_size_xs'] = 'Mindste';
$labels['font_size_s'] = 'Mindre';
$labels['font_size_n'] = 'Normal';
$labels['font_size_l'] = 'Større';
$labels['font_size_xl'] = 'Største';
$labels['setting_thick_font'] = 'Tyk skrifttype';
$labels['setting_font_family'] = 'Skrifttypefamilie';
$labels['setting_color'] = 'Farve';
$labels['save_hint'] = 'Glem ikke at gemme dine indstillinger ved at klikke på knappen "Gem" nedenfor.';

