<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Bedienoberflächeneinstellungen';
$labels['disable_mobile_skin'] = 'Benutze Desktop Skin';
$labels['enable_mobile_skin'] = 'Benutze Mobilen skin';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Skin Einstellungen';
$labels['skin_look_and_feel'] = 'Skin Einstellungen';
$labels['icons'] = 'Icons';
$labels['icons_solid'] = 'Solid';
$labels['icons_traditional'] = 'Traditional';
$labels['icons_outlined'] = 'Outlined';
$labels['icons_material'] = 'Material';
$labels['icons_cartoon'] = 'Cartoon';
$labels['setting_list_icons'] = 'Integriere Icons in Listen';
$labels['setting_button_icons'] = 'Integriere Icons in Knöpfen';
$labels['setting_font_size'] = 'Schriftgröße';
$labels['font_size_xs'] = 'Kleinste';
$labels['font_size_s'] = 'Kleiner';
$labels['font_size_n'] = 'Normal';
$labels['font_size_l'] = 'Größer';
$labels['font_size_xl'] = 'Größte';
$labels['setting_thick_font'] = 'Konturstarke Schrift';
$labels['setting_font_family'] = 'Schriftartenfamilie';
$labels['setting_color'] = 'Farbe';
$labels['save_hint'] = 'Nicht vergessen die Einstellungen per Klick auf den unten stehenden \'Speichern\' Knopf zu sichern.';