<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Επιλογές διασύνδεσης';
$labels['disable_mobile_skin'] = 'Χρήση επιφάνειας εργασίας';
$labels['enable_mobile_skin'] = 'Χρησιμοποιήστε το δέρμα του κινητού';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Εμφάνιση & αίσθηση του δέρματος';
$labels['skin_look_and_feel'] = 'Εμφάνιση & αίσθηση του δέρματος';
$labels['icons'] = 'Εικόνες';
$labels['icons_solid'] = 'Στερεά';
$labels['icons_traditional'] = 'Παραδοσιακό';
$labels['icons_outlined'] = 'Σκιαγραφημένο';
$labels['icons_material'] = 'Υλικό';
$labels['icons_cartoon'] = 'Κινούμενα σχέδια';
$labels['setting_list_icons'] = 'Εικονίδια σε λίστες';
$labels['setting_button_icons'] = 'Εικονίδια στα κουμπιά';
$labels['setting_font_size'] = 'Μέγεθος γραμματοσειράς';
$labels['font_size_xs'] = 'Το μικρότερο';
$labels['font_size_s'] = 'Μικρότερο';
$labels['font_size_n'] = 'Κανονικό';
$labels['font_size_l'] = 'Μεγαλύτερο';
$labels['font_size_xl'] = 'Μεγαλύτερο';
$labels['setting_thick_font'] = 'Παχιά γραμματοσειρά';
$labels['setting_font_family'] = 'Οικογένεια γραμματοσειρών';
$labels['setting_color'] = 'Χρώμα';
$labels['save_hint'] = 'Μην ξεχάσετε να αποθηκεύσετε τις ρυθμίσεις σας κάνοντας κλικ στο κουμπί "Αποθήκευση" παρακάτω.';

