<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Interface Options';
$labels['disable_mobile_skin'] = 'Use desktop skin';
$labels['enable_mobile_skin'] = 'Use mobile skin';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Skin Look & Feel';
$labels['skin_look_and_feel'] = 'Skin Look & Feel';
$labels['icons'] = 'Icons';
$labels['icons_solid'] = 'Solid';
$labels['icons_traditional'] = 'Traditional';
$labels['icons_outlined'] = 'Outlined';
$labels['icons_material'] = 'Material';
$labels['icons_cartoon'] = 'Cartoon';
$labels['setting_list_icons'] = 'Icons in lists';
$labels['setting_button_icons'] = 'Icons on buttons';
$labels['setting_font_size'] = 'Font size';
$labels['font_size_xs'] = 'Smallest';
$labels['font_size_s'] = 'Smaller';
$labels['font_size_n'] = 'Normal';
$labels['font_size_l'] = 'Larger';
$labels['font_size_xl'] = 'Largest';
$labels['setting_thick_font'] = 'Thick font';
$labels['setting_font_family'] = 'Font family';
$labels['setting_color'] = 'Color';
$labels['save_hint'] = 'Don\'t forget to save your settings by clicking the "Save" button below.';

