<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Opsi Antarmuka';
$labels['disable_mobile_skin'] = 'Gunakan kulit desktop';
$labels['enable_mobile_skin'] = 'Gunakan kulit seluler';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Tampilan & Rasa Kulit';
$labels['skin_look_and_feel'] = 'Tampilan & Rasa Kulit';
$labels['icons'] = 'Ikon';
$labels['icons_solid'] = 'Padat';
$labels['icons_traditional'] = 'Tradisional';
$labels['icons_outlined'] = 'Diuraikan';
$labels['icons_material'] = 'Bahan';
$labels['icons_cartoon'] = 'Kartun';
$labels['setting_list_icons'] = 'Ikon dalam daftar';
$labels['setting_button_icons'] = 'Ikon pada tombol';
$labels['setting_font_size'] = 'Ukuran huruf';
$labels['font_size_xs'] = 'Terkecil';
$labels['font_size_s'] = 'Lebih kecil';
$labels['font_size_n'] = 'Normal';
$labels['font_size_l'] = 'Lebih besar';
$labels['font_size_xl'] = 'Terbesar';
$labels['setting_thick_font'] = 'Font tebal';
$labels['setting_font_family'] = 'Keluarga font';
$labels['setting_color'] = 'Warna';
$labels['save_hint'] = 'Jangan lupa untuk menyimpan pengaturan Anda dengan mengeklik tombol "Simpan" di bawah ini.';

