<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Opzioni interfaccia';
$labels['disable_mobile_skin'] = 'Usa tema desktop';
$labels['enable_mobile_skin'] = 'Usa tema mobile';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Aspetto del tema';
$labels['skin_look_and_feel'] = 'Aspetto del tema';
$labels['icons'] = 'Icone';
$labels['icons_solid'] = 'Solido';
$labels['icons_traditional'] = 'Tradizionale';
$labels['icons_outlined'] = 'Delineato';
$labels['icons_material'] = 'Materiale';
$labels['icons_cartoon'] = 'Cartone animato';
$labels['setting_list_icons'] = 'Icone nelle liste';
$labels['setting_button_icons'] = 'Icone sui pulsanti';
$labels['setting_font_size'] = 'Dimensione carattere';
$labels['font_size_xs'] = 'Il più piccolo';
$labels['font_size_s'] = 'Piccolo';
$labels['font_size_n'] = 'Normale';
$labels['font_size_l'] = 'Grande';
$labels['font_size_xl'] = 'Il più grande';
$labels['setting_thick_font'] = 'Carattere spesso';
$labels['setting_font_family'] = 'Famiglia di caratteri';
$labels['setting_color'] = 'Colore';
$labels['save_hint'] = 'Non dimenticare di salvare le tue impostazioni facendo clic sul pulsante "Salva" in basso.';

