<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'インターフェース・オプション';
$labels['disable_mobile_skin'] = 'デスクトップスキンを使用する';
$labels['enable_mobile_skin'] = 'モバイルスキンの使用';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'スキンルック＆フィール';
$labels['skin_look_and_feel'] = 'スキンルック＆フィール';
$labels['icons'] = 'アイコン';
$labels['icons_solid'] = 'ソリッド';
$labels['icons_traditional'] = 'トラディショナル';
$labels['icons_outlined'] = '概要';
$labels['icons_material'] = '素材';
$labels['icons_cartoon'] = '漫画';
$labels['setting_list_icons'] = 'リスト内のアイコン';
$labels['setting_button_icons'] = 'ボタン上のアイコン';
$labels['setting_font_size'] = '文字サイズ';
$labels['font_size_xs'] = '最小';
$labels['font_size_s'] = '小さめ';
$labels['font_size_n'] = 'ノーマル';
$labels['font_size_l'] = 'より大きい';
$labels['font_size_xl'] = '最大';
$labels['setting_thick_font'] = '太いフォント';
$labels['setting_font_family'] = 'フォントファミリー';
$labels['setting_color'] = 'カラー';
$labels['save_hint'] = '下の「保存」ボタンをクリックして設定を保存することをお忘れなく。';

