<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = '인터페이스 옵션';
$labels['disable_mobile_skin'] = '데스크톱 스킨 사용';
$labels['enable_mobile_skin'] = '모바일 스킨 사용';

// elastic based

$labels['skin_look_and_feel_shortcut'] = '피부 룩 & 필';
$labels['skin_look_and_feel'] = '피부 룩 & 필';
$labels['icons'] = '아이콘';
$labels['icons_solid'] = '솔리드';
$labels['icons_traditional'] = '전통';
$labels['icons_outlined'] = '개요';
$labels['icons_material'] = '재료';
$labels['icons_cartoon'] = '카툰';
$labels['setting_list_icons'] = '목록의 아이콘';
$labels['setting_button_icons'] = '버튼의 아이콘';
$labels['setting_font_size'] = '글꼴 크기';
$labels['font_size_xs'] = '가장 작은';
$labels['font_size_s'] = '더 작게';
$labels['font_size_n'] = '보통';
$labels['font_size_l'] = '더 크게';
$labels['font_size_xl'] = '가장 큰';
$labels['setting_thick_font'] = '두꺼운 글꼴';
$labels['setting_font_family'] = '글꼴 패밀리';
$labels['setting_color'] = '색상';
$labels['save_hint'] = '아래의 \'저장\' 버튼을 클릭하여 설정을 저장하는 것을 잊지 마세요.';

