<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Sąsajos parinktys';
$labels['disable_mobile_skin'] = 'Naudoti darbalaukio odą';
$labels['enable_mobile_skin'] = 'Naudokite mobiliąją odą';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Odos išvaizda ir pojūtis';
$labels['skin_look_and_feel'] = 'Odos išvaizda ir pojūtis';
$labels['icons'] = 'Ikonos';
$labels['icons_solid'] = 'Solid';
$labels['icons_traditional'] = 'Tradicinis';
$labels['icons_outlined'] = 'Apibrėžta';
$labels['icons_material'] = 'Medžiaga';
$labels['icons_cartoon'] = 'Karikatūra';
$labels['setting_list_icons'] = 'Ikonos sąrašuose';
$labels['setting_button_icons'] = 'Mygtukų piktogramos';
$labels['setting_font_size'] = 'Šrifto dydis';
$labels['font_size_xs'] = 'Mažiausias';
$labels['font_size_s'] = 'Mažesnis';
$labels['font_size_n'] = 'Normalus';
$labels['font_size_l'] = 'Didesnis';
$labels['font_size_xl'] = 'Didžiausias';
$labels['setting_thick_font'] = 'Storas šriftas';
$labels['setting_font_family'] = 'Šriftų šeima';
$labels['setting_color'] = 'Spalva';
$labels['save_hint'] = 'Nepamirškite išsaugoti nustatymų spustelėdami toliau esantį mygtuką "Išsaugoti".';

