<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Alternativer for grensesnitt';
$labels['disable_mobile_skin'] = 'Bruk skrivebordsskinn';
$labels['enable_mobile_skin'] = 'Bruk mobil hud';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Hudens utseende og følelse';
$labels['skin_look_and_feel'] = 'Hudens utseende og følelse';
$labels['icons'] = 'Ikoner';
$labels['icons_solid'] = 'Solid';
$labels['icons_traditional'] = 'Tradisjonell';
$labels['icons_outlined'] = 'Skissert';
$labels['icons_material'] = 'Materiell';
$labels['icons_cartoon'] = 'Tegneserie';
$labels['setting_list_icons'] = 'Ikoner i lister';
$labels['setting_button_icons'] = 'Ikoner på knapper';
$labels['setting_font_size'] = 'Skriftstørrelse';
$labels['font_size_xs'] = 'Minste';
$labels['font_size_s'] = 'Mindre';
$labels['font_size_n'] = 'Normal';
$labels['font_size_l'] = 'Større';
$labels['font_size_xl'] = 'Største';
$labels['setting_thick_font'] = 'Tykk skrift';
$labels['setting_font_family'] = 'Skriftfamilie';
$labels['setting_color'] = 'Farge';
$labels['save_hint'] = 'Ikke glem å lagre innstillingene dine ved å klikke på "Lagre"-knappen nedenfor.';

