<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Opções de interface';
$labels['disable_mobile_skin'] = 'Usar pele de mesa';
$labels['enable_mobile_skin'] = 'Usar pele móvel';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Olhar e sentir da pele';
$labels['skin_look_and_feel'] = 'Olhar e sentir da pele';
$labels['icons'] = 'Ícones';
$labels['icons_solid'] = 'Sólido';
$labels['icons_traditional'] = 'Tradicional';
$labels['icons_outlined'] = 'Esboçado';
$labels['icons_material'] = 'Material';
$labels['icons_cartoon'] = 'Desenho animado';
$labels['setting_list_icons'] = 'Ícones em listas';
$labels['setting_button_icons'] = 'Ícones nos botões';
$labels['setting_font_size'] = 'Tamanho de letra';
$labels['font_size_xs'] = 'O menor';
$labels['font_size_s'] = 'Menor';
$labels['font_size_n'] = 'Normal';
$labels['font_size_l'] = 'Aumentar';
$labels['font_size_xl'] = 'A maior';
$labels['setting_thick_font'] = 'Fonte espessa';
$labels['setting_font_family'] = 'Família de fontes';
$labels['setting_color'] = 'Cor';
$labels['save_hint'] = 'Não se esqueça de salvar suas configurações, clicando no botão "Salvar" abaixo.';

