<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Opções de interface';
$labels['disable_mobile_skin'] = 'Utilizar a skin do ambiente de trabalho';
$labels['enable_mobile_skin'] = 'Utilizar a pele móvel';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Aspeto e sensação da pele';
$labels['skin_look_and_feel'] = 'Aspeto e sensação da pele';
$labels['icons'] = 'Ícones';
$labels['icons_solid'] = 'Sólido';
$labels['icons_traditional'] = 'Tradicional';
$labels['icons_outlined'] = 'Delineado';
$labels['icons_material'] = 'Material';
$labels['icons_cartoon'] = 'Desenho animado';
$labels['setting_list_icons'] = 'Ícones em listas';
$labels['setting_button_icons'] = 'Ícones nos botões';
$labels['setting_font_size'] = 'Tamanho da letra';
$labels['font_size_xs'] = 'Mais pequeno';
$labels['font_size_s'] = 'Mais pequeno';
$labels['font_size_n'] = 'Normal';
$labels['font_size_l'] = 'Maior';
$labels['font_size_xl'] = 'Maior';
$labels['setting_thick_font'] = 'Tipo de letra espesso';
$labels['setting_font_family'] = 'Família de fontes';
$labels['setting_color'] = 'Cor';
$labels['save_hint'] = 'Não se esqueça de guardar as suas definições clicando no botão "Guardar" abaixo.';

