<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Параметры интерфейса';
$labels['disable_mobile_skin'] = 'Использовать вид рабочего стола';
$labels['enable_mobile_skin'] = 'Использовать вид мобильного';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Внешний вид и ощущения кожи';
$labels['skin_look_and_feel'] = 'Внешний вид и ощущения кожи';
$labels['icons'] = 'Иконки';
$labels['icons_solid'] = 'Твердый';
$labels['icons_traditional'] = 'Традиционный';
$labels['icons_outlined'] = 'Описано';
$labels['icons_material'] = 'Материал';
$labels['icons_cartoon'] = 'Мультфильм';
$labels['setting_list_icons'] = 'Значки в списках';
$labels['setting_button_icons'] = 'Иконки на кнопках';
$labels['setting_font_size'] = 'Размер шрифта';
$labels['font_size_xs'] = 'Самый маленький';
$labels['font_size_s'] = 'Меньше';
$labels['font_size_n'] = 'Нормальный';
$labels['font_size_l'] = 'Крупнее';
$labels['font_size_xl'] = 'Крупнейший';
$labels['setting_thick_font'] = 'Толстый шрифт';
$labels['setting_font_family'] = 'Семейство шрифтов';
$labels['setting_color'] = 'Цвет';
$labels['save_hint'] = 'Не забудьте сохранить настройки, нажав кнопку "Сохранить" ниже.';

