<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Možnosti rozhrania';
$labels['disable_mobile_skin'] = 'Používanie kože na pracovnej ploche';
$labels['enable_mobile_skin'] = 'Používanie mobilnej kože';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Vzhľad a pocit pokožky';
$labels['skin_look_and_feel'] = 'Vzhľad a pocit pokožky';
$labels['icons'] = 'Ikony';
$labels['icons_solid'] = 'Solid';
$labels['icons_traditional'] = 'Tradičné';
$labels['icons_outlined'] = 'Náčrt';
$labels['icons_material'] = 'Materiál';
$labels['icons_cartoon'] = 'Kreslený film';
$labels['setting_list_icons'] = 'Ikony v zoznamoch';
$labels['setting_button_icons'] = 'Ikony na tlačidlách';
$labels['setting_font_size'] = 'Veľkosť písma';
$labels['font_size_xs'] = 'Najmenší';
$labels['font_size_s'] = 'Menšie';
$labels['font_size_n'] = 'Normálne';
$labels['font_size_l'] = 'Väčšie';
$labels['font_size_xl'] = 'Najväčší';
$labels['setting_thick_font'] = 'Hrubé písmo';
$labels['setting_font_family'] = 'Rodina písiem';
$labels['setting_color'] = 'Farba';
$labels['save_hint'] = 'Nezabudnite uložiť svoje nastavenia kliknutím na tlačidlo "Uložiť" nižšie.';

