<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Možnosti vmesnika';
$labels['disable_mobile_skin'] = 'Uporaba namizne kože';
$labels['enable_mobile_skin'] = 'Uporaba mobilne kože';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Videz in občutek kože';
$labels['skin_look_and_feel'] = 'Videz in občutek kože';
$labels['icons'] = 'Ikone';
$labels['icons_solid'] = 'Solid';
$labels['icons_traditional'] = 'Tradicionalni';
$labels['icons_outlined'] = 'Opisano';
$labels['icons_material'] = 'Material';
$labels['icons_cartoon'] = 'Risanka';
$labels['setting_list_icons'] = 'Ikone na seznamih';
$labels['setting_button_icons'] = 'Ikone na gumbih';
$labels['setting_font_size'] = 'Velikost pisave';
$labels['font_size_xs'] = 'Najmanjši';
$labels['font_size_s'] = 'Manjši';
$labels['font_size_n'] = 'Normalno';
$labels['font_size_l'] = 'Večji';
$labels['font_size_xl'] = 'Največji';
$labels['setting_thick_font'] = 'Debela pisava';
$labels['setting_font_family'] = 'Družina pisav';
$labels['setting_color'] = 'Barva';
$labels['save_hint'] = 'Ne pozabite shraniti nastavitev s klikom na spodnji gumb "Shrani".';

