<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Параметри інтерфейсу';
$labels['disable_mobile_skin'] = 'Використовуйте скін робочого столу';
$labels['enable_mobile_skin'] = 'Використовуйте скін мобільного';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Вигляд і відчуття шкіри';
$labels['skin_look_and_feel'] = 'Вигляд і відчуття шкіри';
$labels['icons'] = 'Ікони';
$labels['icons_solid'] = 'Твердий';
$labels['icons_traditional'] = 'Традиційний';
$labels['icons_outlined'] = 'Накреслений';
$labels['icons_material'] = 'Матеріальний';
$labels['icons_cartoon'] = 'Мультяшний';
$labels['setting_list_icons'] = 'Значки в списках';
$labels['setting_button_icons'] = 'Значки на кнопках';
$labels['setting_font_size'] = 'Розмір шрифту';
$labels['font_size_xs'] = 'Найменший';
$labels['font_size_s'] = 'Менший';
$labels['font_size_n'] = 'Нормальний';
$labels['font_size_l'] = 'Більший';
$labels['font_size_xl'] = 'Найбільший';
$labels['setting_thick_font'] = 'Щільний шрифт';
$labels['setting_font_family'] = 'Сімейство шрифтів';
$labels['setting_color'] = 'Колір';
$labels['save_hint'] = 'Не забудьте зберегти свої налаштування, натиснувши кнопку «Зберегти» нижче.';