<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = '接口选项';
$labels['disable_mobile_skin'] = '使用桌面皮肤';
$labels['enable_mobile_skin'] = '使用移动皮肤';

// elastic based

$labels['skin_look_and_feel_shortcut'] = '皮肤外观与触感';
$labels['skin_look_and_feel'] = '皮肤外观与触感';
$labels['icons'] = '图标';
$labels['icons_solid'] = '固体';
$labels['icons_traditional'] = '传统';
$labels['icons_outlined'] = '概述';
$labels['icons_material'] = '材料';
$labels['icons_cartoon'] = '卡通';
$labels['setting_list_icons'] = '列表中的图标';
$labels['setting_button_icons'] = '按钮上的图标';
$labels['setting_font_size'] = '字体大小';
$labels['font_size_xs'] = '最小';
$labels['font_size_s'] = '较小';
$labels['font_size_n'] = '正常';
$labels['font_size_l'] = '更大';
$labels['font_size_xl'] = '最大';
$labels['setting_thick_font'] = '粗字体';
$labels['setting_font_family'] = '字体系列';
$labels['setting_color'] = '颜色';
$labels['save_hint'] = '别忘了点击下面的 "保存 "按钮保存设置。';

