<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = '介面選項';
$labels['disable_mobile_skin'] = '使用桌面皮膚';
$labels['enable_mobile_skin'] = '使用行動皮膚';

// elastic based

$labels['skin_look_and_feel_shortcut'] = '肌膚外觀與觸感';
$labels['skin_look_and_feel'] = '肌膚外觀與觸感';
$labels['icons'] = '圖示';
$labels['icons_solid'] = '堅固';
$labels['icons_traditional'] = '傳統';
$labels['icons_outlined'] = '概述';
$labels['icons_material'] = '材質';
$labels['icons_cartoon'] = '卡通';
$labels['setting_list_icons'] = '清單中的圖示';
$labels['setting_button_icons'] = '按鈕上的圖示';
$labels['setting_font_size'] = '字型大小';
$labels['font_size_xs'] = '最小';
$labels['font_size_s'] = '較小';
$labels['font_size_n'] = '正常';
$labels['font_size_l'] = '較大';
$labels['font_size_xl'] = '最大';
$labels['setting_thick_font'] = '粗體字';
$labels['setting_font_family'] = '字型系列';
$labels['setting_color'] = '顏色';
$labels['save_hint'] = '別忘了按一下下方的「儲存」按鈕來儲存您的設定。';

