<?php

/**
 * Roundcube Loader Plugin — German localization
 *
 * @license GNU GPLv3+
 */

$labels = [];
$labels['roundcube_loader'] = 'Ladebildschirm';
$labels['loading'] = 'Wird geladen...';
$labels['loading_user'] = '%s wird geladen...';
$labels['signing_in'] = 'Anmeldung läuft...';
$labels['standard_view'] = 'Standardansicht';
$labels['load_basic_html'] = 'Einfaches HTML laden';
$labels['slow_connections'] = 'für langsame Verbindungen';
$labels['taking_longer'] = 'Dauert es länger als gewöhnlich?';
$labels['reload'] = 'Hier klicken zum Neuladen';
$labels['enable_loader'] = 'Gmail-Ladebildschirm aktivieren';
$labels['loader_theme'] = 'Design des Ladebildschirms';
$labels['theme_gmail'] = 'Gmail Rot';
$labels['theme_google_gradient'] = 'Google 4-Farben-Verlauf';
$labels['theme_roundcube'] = 'Roundcube Blau';
