<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'خيارات الواجهة';
$labels['disable_mobile_skin'] = 'استخدام مظهر سطح المكتب';
$labels['enable_mobile_skin'] = 'استخدام بشرة الهاتف المحمول';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'مظهر البشرة وملمسها';
$labels['skin_look_and_feel'] = 'مظهر البشرة وملمسها';
$labels['icons'] = 'الأيقونات';
$labels['icons_solid'] = 'صلبة';
$labels['icons_traditional'] = 'تقليدي';
$labels['icons_outlined'] = 'الخطوط العريضة';
$labels['icons_material'] = 'المواد';
$labels['icons_cartoon'] = 'رسوم متحركة';
$labels['setting_list_icons'] = 'الأيقونات في القوائم';
$labels['setting_button_icons'] = 'أيقونات على الأزرار';
$labels['setting_font_size'] = 'حجم الخط';
$labels['font_size_xs'] = 'الأصغر';
$labels['font_size_s'] = 'أصغر';
$labels['font_size_n'] = 'عادي';
$labels['font_size_l'] = 'أكبر';
$labels['font_size_xl'] = 'الأكبر';
$labels['setting_thick_font'] = 'خط سميك';
$labels['setting_font_family'] = 'عائلة الخط';
$labels['setting_color'] = 'اللون';
$labels['save_hint'] = 'لا تنسَ حفظ إعداداتك بالنقر على زر "حفظ" أدناه.';

