<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Liitäntäasetukset';
$labels['disable_mobile_skin'] = 'Käytä työpöydän ihoa';
$labels['enable_mobile_skin'] = 'Käytä mobiili-ihoa';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Ihon ulkoasu & tuntuma';
$labels['skin_look_and_feel'] = 'Ihon ulkoasu & tuntuma';
$labels['icons'] = 'Kuvakkeet';
$labels['icons_solid'] = 'Solid';
$labels['icons_traditional'] = 'Perinteinen';
$labels['icons_outlined'] = 'Hahmoteltu';
$labels['icons_material'] = 'Materiaali';
$labels['icons_cartoon'] = 'Sarjakuva';
$labels['setting_list_icons'] = 'Kuvakkeet luetteloissa';
$labels['setting_button_icons'] = 'Kuvakkeet painikkeissa';
$labels['setting_font_size'] = 'Kirjasinkoko';
$labels['font_size_xs'] = 'Pienin';
$labels['font_size_s'] = 'Pienempi';
$labels['font_size_n'] = 'Normaali';
$labels['font_size_l'] = 'Suurempi';
$labels['font_size_xl'] = 'Suurin';
$labels['setting_thick_font'] = 'Paksu fontti';
$labels['setting_font_family'] = 'Fonttiperhe';
$labels['setting_color'] = 'Väri';
$labels['save_hint'] = 'Muista tallentaa asetukset napsauttamalla alla olevaa "Tallenna"-painiketta.';

