<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Options de l\'interface';
$labels['disable_mobile_skin'] = 'Utiliser le thème bureau';
$labels['enable_mobile_skin'] = 'Utiliser le thème mobile';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Paramètres du thème';
$labels['skin_look_and_feel'] = 'Apparence du thème';
$labels['icons'] = 'Icônes';
$labels['icons_solid'] = 'Solide';
$labels['icons_traditional'] = 'Traditionnel';
$labels['icons_outlined'] = 'Contour';
$labels['icons_material'] = 'Matière';
$labels['icons_cartoon'] = 'Dessin';
$labels['setting_list_icons'] = 'Icônes dans les listes';
$labels['setting_button_icons'] = 'Icônes sur les boutons';
$labels['setting_font_size'] = 'Taille de la police';
$labels['font_size_xs'] = 'Le plus petit';
$labels['font_size_s'] = 'Plus petit';
$labels['font_size_n'] = 'Normal';
$labels['font_size_l'] = 'Plus grand';
$labels['font_size_xl'] = 'Le plus grand';
$labels['setting_thick_font'] = 'Police épaisse';
$labels['setting_font_family'] = 'Famille de police';
$labels['setting_color'] = 'Couleur';
$labels['save_hint'] = 'N\'oubliez pas de sauvegarder vos paramètres en cliquant sur le bouton \'Enregistrer\' ci-dessous.';

