<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Interfész opciók';
$labels['disable_mobile_skin'] = 'Asztali skin használata';
$labels['enable_mobile_skin'] = 'Mobil skin használata';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Bőr megjelenés és érzés';
$labels['skin_look_and_feel'] = 'Bőr megjelenés és érzés';
$labels['icons'] = 'Ikonok';
$labels['icons_solid'] = 'Szilárd';
$labels['icons_traditional'] = 'Hagyományos';
$labels['icons_outlined'] = 'Vázlatos';
$labels['icons_material'] = 'Anyag';
$labels['icons_cartoon'] = 'Rajzfilm';
$labels['setting_list_icons'] = 'Ikonok a listákban';
$labels['setting_button_icons'] = 'Ikonok a gombokon';
$labels['setting_font_size'] = 'Betűméret';
$labels['font_size_xs'] = 'Legkisebb';
$labels['font_size_s'] = 'Kisebb';
$labels['font_size_n'] = 'Normál';
$labels['font_size_l'] = 'Nagyobb';
$labels['font_size_xl'] = 'Legnagyobb';
$labels['setting_thick_font'] = 'Vastag betűtípus';
$labels['setting_font_family'] = 'Betűcsalád';
$labels['setting_color'] = 'Színes';
$labels['save_hint'] = 'Ne felejtse el elmenteni a beállításokat az alábbi "Mentés" gombra kattintva.';

