<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Saskarnes opcijas';
$labels['disable_mobile_skin'] = 'Darbvirsmas ādas lietošana';
$labels['enable_mobile_skin'] = 'Izmantojiet mobilo ādu';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Ādas izskats un sajūta';
$labels['skin_look_and_feel'] = 'Ādas izskats un sajūta';
$labels['icons'] = 'Ikonas';
$labels['icons_solid'] = 'Solid';
$labels['icons_traditional'] = 'Tradicionālais';
$labels['icons_outlined'] = 'Izklāstīts';
$labels['icons_material'] = 'Materiāls';
$labels['icons_cartoon'] = 'Karikatūra';
$labels['setting_list_icons'] = 'Ikonas sarakstos';
$labels['setting_button_icons'] = 'Ikonas uz pogām';
$labels['setting_font_size'] = 'Fonta lielums';
$labels['font_size_xs'] = 'Mazākais';
$labels['font_size_s'] = 'Mazāks';
$labels['font_size_n'] = 'Parasts';
$labels['font_size_l'] = 'Lielāks';
$labels['font_size_xl'] = 'Lielākais';
$labels['setting_thick_font'] = 'Biezs fonts';
$labels['setting_font_family'] = 'Fontu ģimene';
$labels['setting_color'] = 'Krāsa';
$labels['save_hint'] = 'Neaizmirstiet saglabāt iestatījumus, noklikšķinot uz zemāk redzamās pogas "Saglabāt".';

