<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Opcje interfejsu';
$labels['disable_mobile_skin'] = 'Użyj skórki na desktop';
$labels['enable_mobile_skin'] = 'Użycie skórki mobilnej';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Ustawienia wyglądu';
$labels['skin_look_and_feel'] = 'Ustawienia wyglądu';
$labels['icons'] = 'Ikony';
$labels['icons_solid'] = 'Masywne';
$labels['icons_traditional'] = 'Tradycjonalne';
$labels['icons_outlined'] = 'Nakreślone';
$labels['icons_material'] = 'Materiałowe';
$labels['icons_cartoon'] = 'Kreskówkowe';
$labels['setting_list_icons'] = 'Ikony na listach';
$labels['setting_button_icons'] = 'Ikony na przyciskach';
$labels['setting_font_size'] = 'Rozmiar czcionki';
$labels['font_size_xs'] = 'Najmniejsza';
$labels['font_size_s'] = 'Mniejsza';
$labels['font_size_n'] = 'Normalna';
$labels['font_size_l'] = 'Większa';
$labels['font_size_xl'] = 'Największa';
$labels['setting_thick_font'] = 'Gruba czcionka';
$labels['setting_font_family'] = 'Rodzina czcionek';
$labels['setting_color'] = 'Kolor';
$labels['save_hint'] = 'Nie zapomnij zapisać swoich ustawień klikając przycisk "Zapisz" poniżej.';