<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Arayüz Seçenekleri';
$labels['disable_mobile_skin'] = 'Masaüstü görünümünü kullanma';
$labels['enable_mobile_skin'] = 'Mobil cilt kullanın';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Cilt Görünümü ve Hissi';
$labels['skin_look_and_feel'] = 'Cilt Görünümü ve Hissi';
$labels['icons'] = 'Simgeler';
$labels['icons_solid'] = 'Katı';
$labels['icons_traditional'] = 'Geleneksel';
$labels['icons_outlined'] = 'Ana hatlarıyla';
$labels['icons_material'] = 'Malzeme';
$labels['icons_cartoon'] = 'Karikatür';
$labels['setting_list_icons'] = 'Listelerdeki simgeler';
$labels['setting_button_icons'] = 'Düğmelerdeki simgeler';
$labels['setting_font_size'] = 'Yazı tipi boyutu';
$labels['font_size_xs'] = 'En küçük';
$labels['font_size_s'] = 'Daha küçük';
$labels['font_size_n'] = 'Normal';
$labels['font_size_l'] = 'Daha büyük';
$labels['font_size_xl'] = 'En büyük';
$labels['setting_thick_font'] = 'Kalın yazı tipi';
$labels['setting_font_family'] = 'Yazı tipi ailesi';
$labels['setting_color'] = 'Renk';
$labels['save_hint'] = 'Aşağıdaki "Kaydet" düğmesine tıklayarak ayarlarınızı kaydetmeyi unutmayın.';

