<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Přidej odkaz do zpráv';
$labels['download_and_attach'] = 'Stáhni a přilož';
$labels['sidebar'] = 'Postranní panel';
$labels['sidebar_items'] = 'Položky postranního panelu';
$labels['sidebar_change_order'] = 'Chyť a pusť změna pořadí položek';
$labels['preview'] = 'Náhled';
$labels['apps'] = 'Aplikace';
$labels['sidebar'] = 'Postranní panel';
$labels['hide'] = 'Skrýt';
$labels['invalid_image_extension'] = 'Špatný typ přílohy, povolené jsou: $ext';
$labels['invalid_image_format'] = 'Soubor neobsahuje obrázek nebo špatný typ obrázku';
$labels['copy_to_clipboard'] = 'Kopírování do schránky';
$labels['copied_to_clipboard'] = 'Zkopírováno do schránky.';
$labels['cannot_copy_to_clipboard'] = 'Nelze zkopírovat text do schránky.';
