<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Link zur Nachricht einfügen';
$labels['download_and_attach'] = 'Herunterladen und hinzufügen';
$labels['sidebar'] = 'Sidebar';
$labels['sidebar_items'] = 'Sidebar-Elemente';
$labels['sidebar_change_order'] = 'Verschieben Sie die Sidebar-Elemente per Drag&Drop, um ihre Reihenfolge zu ändern.';
$labels['preview'] = 'Vorschau';
$labels['apps'] = 'Apps';
$labels['sidebar'] = 'Sidebar';
$labels['hide'] = 'Ausblenden';
$labels['invalid_image_extension'] = 'Ungültige Dateiendung. Erlaubte Endungen: $ext';
$labels['invalid_image_format'] = 'Die Datei ist kein gültiges Bild';
$labels['copy_to_clipboard'] = 'In die Zwischenablage kopieren';
$labels['copied_to_clipboard'] = 'In die Zwischenablage kopiert.';
$labels['cannot_copy_to_clipboard'] = 'Text kann nicht in die Zwischenablage kopiert werden.';
