<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Insert link to message';
$labels['download_and_attach'] = 'Download and attach';
$labels['sidebar'] = 'Sidebar';
$labels['sidebar_items'] = 'Sidebar items';
$labels['sidebar_change_order'] = 'Drag and drop sidebar items to change their order.';
$labels['preview'] = 'Preview';
$labels['apps'] = 'Apps';
$labels['sidebar'] = 'Sidebar';
$labels['hide'] = 'Hide';
$labels['invalid_image_extension'] = 'Invalid image file extension. The allowed extensions are: $ext.';
$labels['invalid_image_format'] = 'This file is not a valid image.';
$labels['copy_to_clipboard'] = 'Copy to clipboard';
$labels['copied_to_clipboard'] = 'Copied to clipboard.';
$labels['cannot_copy_to_clipboard'] = 'Cannot copy text to clipboard.';