<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Insertar enlace al mensaje';
$labels['download_and_attach'] = 'Descargar y adjuntar';
$labels['sidebar'] = 'Barra lateral';
$labels['sidebar_items'] = 'Elementos de la barra lateral';
$labels['sidebar_change_order'] = 'Arrastre y suelte los elementos de la barra lateral para cambiar su orden.';
$labels['preview'] = 'Vista previa';
$labels['apps'] = 'Aplicaciones';
$labels['sidebar'] = 'Barra lateral';
$labels['hide'] = 'Ocultar';
$labels['invalid_image_extension'] = 'Extensión de archivo de imagen no válida. Las extensiones permitidas son: $ext.';
$labels['invalid_image_format'] = 'Este archivo no es una imagen válida.';
$labels['copy_to_clipboard'] = 'Copiar al portapapeles';
$labels['copied_to_clipboard'] = 'Copiado al portapapeles.';
$labels['cannot_copy_to_clipboard'] = 'No se puede copiar texto en el portapapeles.';
