<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Lisää linkki viestiin';
$labels['download_and_attach'] = 'Lataa ja liitä';
$labels['sidebar'] = 'Sivupalkki';
$labels['sidebar_items'] = 'Sivupalkin kohteet';
$labels['sidebar_change_order'] = 'Voit muuttaa sivupalkin kohteiden järjestystä vetämällä ja pudottamalla niitä.';
$labels['preview'] = 'Esikatselu';
$labels['apps'] = 'Sovellukset';
$labels['sidebar'] = 'Sivupalkki';
$labels['hide'] = 'Piilota';
$labels['invalid_image_extension'] = 'Virheellinen kuvatiedoston laajennus. Sallitut laajennukset ovat: $ext.';
$labels['invalid_image_format'] = 'Tämä tiedosto ei ole kelvollinen kuva.';
$labels['copy_to_clipboard'] = 'Kopioi leikepöydälle';
$labels['copied_to_clipboard'] = 'Kopioitu leikepöydälle.';
$labels['cannot_copy_to_clipboard'] = 'Tekstiä ei voi kopioida leikepöydälle.';
