<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Insérer un lien vers le message';
$labels['download_and_attach'] = 'Télécharger et joindre';
$labels['sidebar'] = 'Sidebar';
$labels['sidebar_items'] = 'Éléments de la barre latérale';
$labels['sidebar_change_order'] = 'Faites glisser et déposez les éléments de la barre latérale pour modifier leur ordre.';
$labels['preview'] = 'Aperçu';
$labels['apps'] = 'Apps';
$labels['sidebar'] = 'Sidebar';
$labels['hide'] = 'Cacher';
$labels['invalid_image_extension'] = 'Extension d\'image non valide. Les extensions autorisées sont : $ext';
$labels['invalid_image_format'] = 'Ce fichier n\'est pas une image valide.';
$labels['copy_to_clipboard'] = 'Copier dans le presse-papiers';
$labels['copied_to_clipboard'] = 'Copié dans le presse-papiers.';
$labels['cannot_copy_to_clipboard'] = 'Impossible de copier le texte dans le presse-papiers.';
