<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google disks';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Ievietot saiti uz ziņojumu';
$labels['download_and_attach'] = 'Lejupielādēt un pievienot';
$labels['sidebar'] = 'Sānu josla';
$labels['sidebar_items'] = 'Sānu joslas elementi';
$labels['sidebar_change_order'] = 'Velciet un nometiet sānjoslas vienumus, lai mainītu to secību.';
$labels['preview'] = 'Priekšskatījums';
$labels['apps'] = 'Aplikācijas';
$labels['sidebar'] = 'Sānu josla';
$labels['hide'] = 'Paslēpt';
$labels['invalid_image_extension'] = 'Nederīgs attēla faila paplašinājums. Atļautie paplašinājumi ir šādi: $ext.';
$labels['invalid_image_format'] = 'Šis fails nav derīgs attēls.';
$labels['copy_to_clipboard'] = 'Kopēt uz starpliktuvi';
$labels['copied_to_clipboard'] = 'Kopēts uz starpliktuvi.';
$labels['cannot_copy_to_clipboard'] = 'Nevar kopēt tekstu uz starpliktuvi.';
