<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Disk';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Sett inn lenke til melding';
$labels['download_and_attach'] = 'Last ned og legg ved';
$labels['sidebar'] = 'Sidefelt';
$labels['sidebar_items'] = 'Elementer i sidepanelet';
$labels['sidebar_change_order'] = 'Dra og slipp elementer i sidepanelet for å endre rekkefølgen.';
$labels['preview'] = 'Forhåndsvisning';
$labels['apps'] = 'Apper';
$labels['sidebar'] = 'Sidefelt';
$labels['hide'] = 'Skjul';
$labels['invalid_image_extension'] = 'Ugyldig filtype for bildefil. De tillatte filtypene er: $ext.';
$labels['invalid_image_format'] = 'Denne filen er ikke et gyldig bilde.';
$labels['copy_to_clipboard'] = 'Kopier til utklippstavlen';
$labels['copied_to_clipboard'] = 'Kopieres til utklippstavlen.';
$labels['cannot_copy_to_clipboard'] = 'Kan ikke kopiere tekst til utklippstavlen.';
