<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Inserir ligação à mensagem';
$labels['download_and_attach'] = 'Descarregar e anexar';
$labels['sidebar'] = 'Barra lateral';
$labels['sidebar_items'] = 'Itens da barra lateral';
$labels['sidebar_change_order'] = 'Arraste e largue os itens da barra lateral para alterar a sua ordem.';
$labels['preview'] = 'Pré-visualização';
$labels['apps'] = 'Aplicações';
$labels['sidebar'] = 'Barra lateral';
$labels['hide'] = 'Esconder';
$labels['invalid_image_extension'] = 'Extensão de ficheiro de imagem inválida. As extensões permitidas são: $ext.';
$labels['invalid_image_format'] = 'Este ficheiro não é uma imagem válida.';
$labels['copy_to_clipboard'] = 'Copiar para a área de transferência';
$labels['copied_to_clipboard'] = 'Copiado para a área de transferência.';
$labels['cannot_copy_to_clipboard'] = 'Não é possível copiar texto para a área de transferência.';
