<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Introduceți un link către mesaj';
$labels['download_and_attach'] = 'Descărcați și atașați';
$labels['sidebar'] = 'Bara laterală';
$labels['sidebar_items'] = 'Elemente din bara laterală';
$labels['sidebar_change_order'] = 'Trageți și fixați elementele din bara laterală pentru a le schimba ordinea.';
$labels['preview'] = 'Previzualizare';
$labels['apps'] = 'Aplicații';
$labels['sidebar'] = 'Bara laterală';
$labels['hide'] = 'Ascundeți';
$labels['invalid_image_extension'] = 'Extensie de fișier imagine invalidă. Extensiile permise sunt: $ext.';
$labels['invalid_image_format'] = 'Acest fișier nu este o imagine validă.';
$labels['copy_to_clipboard'] = 'Copiere în clipboard';
$labels['copied_to_clipboard'] = 'Copiat în clipboard.';
$labels['cannot_copy_to_clipboard'] = 'Nu se poate copia text în clipboard.';
