<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Infoga länk till meddelande';
$labels['download_and_attach'] = 'Ladda ner och bifoga';
$labels['sidebar'] = 'Sidofält';
$labels['sidebar_items'] = 'Objekt i sidofältet';
$labels['sidebar_change_order'] = 'Dra och släpp sidofältets objekt för att ändra deras ordning.';
$labels['preview'] = 'Förhandsgranskning';
$labels['apps'] = 'Appar';
$labels['sidebar'] = 'Sidofält';
$labels['hide'] = 'Göm dig';
$labels['invalid_image_extension'] = 'Ogiltig bildfilstillägg. De tillåtna filtilläggen är: $ext.';
$labels['invalid_image_format'] = 'Den här filen är inte en giltig bild.';
$labels['copy_to_clipboard'] = 'Kopiera till urklipp';
$labels['copied_to_clipboard'] = 'Kopieras till urklipp.';
$labels['cannot_copy_to_clipboard'] = 'Det går inte att kopiera text till urklipp.';
