<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'ставити посилання в повідомлення';
$labels['download_and_attach'] = 'Завантаити та додати';
$labels['sidebar'] = 'Бічна панель';
$labels['sidebar_items'] = 'Елементи бічної панелі';
$labels['sidebar_change_order'] = 'Перетягніть елементи бічної панелі, щоб змінити їх розташування.';
$labels['preview'] = 'Попередній перегляд';
$labels['apps'] = 'Програми';
$labels['sidebar'] = 'Бічна панель';
$labels['hide'] = 'Приховати';
$labels['invalid_image_extension'] = 'Недійсне розширення зображення. Дозволеними розширеннями є: $ext.';
$labels['invalid_image_format'] = 'Цей файл не є дійсним зображенням.';
$labels['copy_to_clipboard'] = 'Скопіювати в буфер обміну';
$labels['copied_to_clipboard'] = 'Скопійовано в буфер обміну.';
$labels['cannot_copy_to_clipboard'] = 'Не вдається скопіювати текст до буфера обміну.';
