<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = '谷歌硬盘';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = '插入信息链接';
$labels['download_and_attach'] = '下载并附加';
$labels['sidebar'] = '侧边栏';
$labels['sidebar_items'] = '侧边栏项目';
$labels['sidebar_change_order'] = '拖放侧边栏项目可更改其顺序。';
$labels['preview'] = '预览';
$labels['apps'] = '应用程序';
$labels['sidebar'] = '侧边栏';
$labels['hide'] = '隐藏';
$labels['invalid_image_extension'] = '图像文件扩展名无效。允许的扩展名有$ext.';
$labels['invalid_image_format'] = '该文件不是有效图像。';
$labels['copy_to_clipboard'] = '复制到剪贴板';
$labels['copied_to_clipboard'] = '复制到剪贴板。';
$labels['cannot_copy_to_clipboard'] = '无法将文本复制到剪贴板。';
