<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = '插入訊息連結';
$labels['download_and_attach'] = '下載並附加';
$labels['sidebar'] = '側邊欄';
$labels['sidebar_items'] = '側邊欄項目';
$labels['sidebar_change_order'] = '拖放側邊欄項目可變更其順序。';
$labels['preview'] = '預覽';
$labels['apps'] = '應用程式';
$labels['sidebar'] = '側邊欄';
$labels['hide'] = '隱藏';
$labels['invalid_image_extension'] = '影像檔案副檔名無效。允許的副檔名為$ext.';
$labels['invalid_image_format'] = '此檔案不是有效的影像。';
$labels['copy_to_clipboard'] = '複製到剪貼簿';
$labels['copied_to_clipboard'] = '複製到剪貼簿。';
$labels['cannot_copy_to_clipboard'] = '無法將文字複製到剪貼簿。';
