CREATE TABLE IF NOT EXISTS xcalendar_published (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INT UNSIGNED NOT NULL DEFAULT 0,
    calendar_id INT UNSIGNED NOT NULL DEFAULT 0,
    code VARCHAR(255) NOT NULL DEFAULT '',
    full TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS code ON xcalendar_published (code);