CREATE TABLE IF NOT EXISTS xcalendar_attendees (
    event_id INT UNSIGNED NOT NULL DEFAULT 0,
    calendar_id INT UNSIGNED NOT NULL DEFAULT 0,
    email VARCHAR(255) NOT NULL DEFAULT '',
    name VARCHAR(255) NOT NULL DEFAULT '', /* CN */
    code VARCHAR(40) NOT NULL DEFAULT '',
    organizer TINYINT(1) NOT NULL DEFAULT 0,
    role TINYINT(1) NOT NULL DEFAULT 0, /* 0 = REQ-PARTICIPANT, 1 = OPT-PARTICIPANT, 2 = NON-PARTICIPANT, 3 = CHAIR */
    hidden TINYINT(1) NOT NULL DEFAULT 0,
    can_see_attendees TINYINT(1) NOT NULL DEFAULT 1,
    notify TINYINT(1) NOT NULL DEFAULT 1,
    status TINYINT(1) NOT NULL DEFAULT 0, /* 0 = NEEDS-ACTION, 1 = ACCEPTED, 2 = DECLINED, 3 = TENTATIVE, 4 = DELEGATED */
    guests INT UNSIGNED NOT NULL DEFAULT 0, /* X-NUM-GUESTS */
    comment VARCHAR(255) NOT NULL DEFAULT '', /* X-RESPONSE-COMMENT */
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    responded_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (event_id, email),
    INDEX `code`(code)
) ENGINE = InnoDB DEFAULT CHARSET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE xcalendar_events ADD has_attendees TINYINT(1) DEFAULT 0;
