<?php
/**
 * Roundcube Plus Multibox plugin.
 *
 * Copyright 2023, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['plugin_name'] = 'مالتي بوكس';
$labels['app_menu_title'] = 'خوادم البريد المخصصة';
$labels['custom_email_account'] = 'حساب بريد إلكتروني مخصص';
$labels['use_custom_mail_servers'] = 'استخدام خوادم بريد مخصصة';
$labels['incoming_server'] = 'الخادم الوارد (IMAP)';
$labels['outgoing_server'] = 'الخادم الصادر (SMTP)';

$labels['server'] = 'الخادم';
$labels['port'] = 'الميناء';
$labels['connection_security'] = 'أمان الاتصال';
$labels['authentication'] = 'المصادقة';
$labels['test_connection'] = 'اختبار الاتصال';
$labels['use_imap_user_pass'] = 'استخدام اسم مستخدم وكلمة مرور IMAP';
$labels['specify_user_pass'] = 'تحديد اسم المستخدم وكلمة المرور';

$labels['validation_required'] = '$ f مطلوب.';
$labels['validation_maxlen'] = 'يجب أن يكون حرف $ f أقصر من حرف $ n.';
$labels['validation_port'] = 'يجب أن يكون $ f عددًا صحيحًا في النطاق 1-65535.';

$labels['login_successful'] = 'تم تسجيل الدخول بنجاح.';
$labels['text_in_parentheses'] = '($s)';
$labels['cannot_login_to_imap_server'] = 'لا يمكن تسجيل الدخول إلى خادم IMAP.';
$labels['cannot_login_to_smtp_server'] = 'لا يمكن تسجيل الدخول إلى خادم SMTP.';
$labels['cannot_save_multibox_data'] = 'لا يمكن حفظ البيانات متعددة الصناديق.';
$labels['settings_not_saved'] = 'الإعدادات غير محفوظة.';
