<?php
/**
 * Roundcube Plus Multibox plugin.
 *
 * Copyright 2023, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['plugin_name'] = 'Multibox';
$labels['app_menu_title'] = 'Потребителски пощенски сървъри';
$labels['custom_email_account'] = 'Персонализиран акаунт за електронна поща';
$labels['use_custom_mail_servers'] = 'Използване на персонализирани пощенски сървъри';
$labels['incoming_server'] = 'Входящ сървър (IMAP)';
$labels['outgoing_server'] = 'Изходящ сървър (SMTP)';

$labels['server'] = 'Сървър';
$labels['port'] = 'Пристанище';
$labels['connection_security'] = 'Сигурност на връзката';
$labels['authentication'] = 'Удостоверяване';
$labels['test_connection'] = 'Проверка на връзката';
$labels['use_imap_user_pass'] = 'Използване на потребителско име и парола на IMAP';
$labels['specify_user_pass'] = 'Посочете потребителско име и парола';

$labels['validation_required'] = 'Изисква се $f.';
$labels['validation_maxlen'] = '$f трябва да е по-кратък от $n символа.';
$labels['validation_port'] = '$f трябва да бъде цяло число в интервала 1-65535.';

$labels['login_successful'] = 'Влизането е успешно.';
$labels['text_in_parentheses'] = '($s)';
$labels['cannot_login_to_imap_server'] = 'Не можете да влезете в IMAP сървъра.';
$labels['cannot_login_to_smtp_server'] = 'Не можете да влезете в SMTP сървъра.';
$labels['cannot_save_multibox_data'] = 'Не може да се запазят данни от няколко полета.';
$labels['settings_not_saved'] = 'Настройките не са запазени.';
