<?php
/**
 * Roundcube Plus Multibox plugin.
 *
 * Copyright 2023, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['plugin_name'] = 'Multibox';
$labels['app_menu_title'] = 'Tilpassede mailservere';
$labels['custom_email_account'] = 'Brugerdefineret e-mail-konto';
$labels['use_custom_mail_servers'] = 'Brug tilpassede mailservere';
$labels['incoming_server'] = 'Indgående server (IMAP)';
$labels['outgoing_server'] = 'Udgående server (SMTP)';

$labels['server'] = 'Server';
$labels['port'] = 'Port';
$labels['connection_security'] = 'Forbindelsessikkerhed';
$labels['authentication'] = 'Godkendelse';
$labels['test_connection'] = 'Test forbindelse';
$labels['use_imap_user_pass'] = 'Brug IMAP-brugernavn og -adgangskode';
$labels['specify_user_pass'] = 'Angiv brugernavn og adgangskode';

$labels['validation_required'] = '$f: obligatorisk felt.';
$labels['validation_maxlen'] = '$f: skal være kortere end $n tegn.';
$labels['validation_port'] = '$f skal være et heltal i intervallet 1-65535.';

$labels['login_successful'] = 'Login lykkedes.';
$labels['text_in_parentheses'] = '($s)';
$labels['cannot_login_to_imap_server'] = 'Kan ikke logge ind på IMAP-serveren.';
$labels['cannot_login_to_smtp_server'] = 'Kan ikke logge ind på SMTP-serveren.';
$labels['cannot_save_multibox_data'] = 'Kan ikke gemme multibox-data.';
$labels['settings_not_saved'] = 'Indstillingerne er ikke gemt.';
