<?php
/**
 * Roundcube Plus Multibox plugin.
 *
 * Copyright 2023, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['plugin_name'] = 'Multibox';
$labels['app_menu_title'] = 'Προσαρμοσμένοι διακομιστές αλληλογραφίας';
$labels['custom_email_account'] = 'Προσαρμοσμένος λογαριασμός e-mail';
$labels['use_custom_mail_servers'] = 'Χρήση προσαρμοσμένων διακομιστών αλληλογραφίας';
$labels['incoming_server'] = 'Εισερχόμενος διακομιστής (IMAP)';
$labels['outgoing_server'] = 'Διακομιστής εξερχόμενων (SMTP)';

$labels['server'] = 'Διακομιστής';
$labels['port'] = 'Λιμάνι';
$labels['connection_security'] = 'Ασφάλεια σύνδεσης';
$labels['authentication'] = 'Αυθεντικοποίηση';
$labels['test_connection'] = 'Σύνδεση δοκιμής';
$labels['use_imap_user_pass'] = 'Χρήση ονόματος χρήστη και κωδικού πρόσβασης IMAP';
$labels['specify_user_pass'] = 'Καθορίστε το όνομα χρήστη και τον κωδικό πρόσβασης';

$labels['validation_required'] = 'Απαιτείται $f.';
$labels['validation_maxlen'] = 'Το $f πρέπει να είναι μικρότερο από $n χαρακτήρες.';
$labels['validation_port'] = 'Το $f πρέπει να είναι ένας ακέραιος αριθμός στο εύρος 1-65535.';

$labels['login_successful'] = 'Σύνδεση επιτυχής.';
$labels['text_in_parentheses'] = '($s)';
$labels['cannot_login_to_imap_server'] = 'Δεν είναι δυνατή η σύνδεση στο διακομιστή IMAP.';
$labels['cannot_login_to_smtp_server'] = 'Δεν είναι δυνατή η σύνδεση στο διακομιστή SMTP.';
$labels['cannot_save_multibox_data'] = 'Δεν είναι δυνατή η αποθήκευση δεδομένων πολλαπλών κιβωτίων.';
$labels['settings_not_saved'] = 'Οι ρυθμίσεις δεν έχουν αποθηκευτεί.';
