<?php
/**
 * Roundcube Plus Multibox plugin.
 *
 * Copyright 2023, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['plugin_name'] = 'Multibox';
$labels['app_menu_title'] = 'Kohandatud e-posti serverid';
$labels['custom_email_account'] = 'Kohandatud e-posti konto';
$labels['use_custom_mail_servers'] = 'Kasutage kohandatud e-posti servereid';
$labels['incoming_server'] = 'Saabuv server (IMAP)';
$labels['outgoing_server'] = 'Väljaminev server (SMTP)';

$labels['server'] = 'Server';
$labels['port'] = 'Sadam';
$labels['connection_security'] = 'Ühenduse turvalisus';
$labels['authentication'] = 'Autentimine';
$labels['test_connection'] = 'Testühendus';
$labels['use_imap_user_pass'] = 'Kasutage IMAPi kasutajanime ja parooli';
$labels['specify_user_pass'] = 'Määrake kasutajanimi ja parool';

$labels['validation_required'] = '$f on nõutav.';
$labels['validation_maxlen'] = '$f peab olema lühem kui $n märki.';
$labels['validation_port'] = '$f peab olema täisarv vahemikus 1-65535.';

$labels['login_successful'] = 'Sisselogimine õnnestus.';
$labels['text_in_parentheses'] = '($s)';
$labels['cannot_login_to_imap_server'] = 'Ei saa IMAP-serverisse sisse logida.';
$labels['cannot_login_to_smtp_server'] = 'SMTP-serverisse ei saa sisse logida.';
$labels['cannot_save_multibox_data'] = 'Ei saa salvestada mitme kasti andmeid.';
$labels['settings_not_saved'] = 'Seaded ei ole salvestatud.';
