<?php
/**
 * Roundcube Plus Multibox plugin.
 *
 * Copyright 2023, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['plugin_name'] = 'Multibox';
$labels['app_menu_title'] = 'Server Surat Khusus';
$labels['custom_email_account'] = 'Akun Email Khusus';
$labels['use_custom_mail_servers'] = 'Menggunakan server email khusus';
$labels['incoming_server'] = 'Server Masuk (IMAP)';
$labels['outgoing_server'] = 'Server Keluar (SMTP)';

$labels['server'] = 'Server';
$labels['port'] = 'Pelabuhan';
$labels['connection_security'] = 'Keamanan koneksi';
$labels['authentication'] = 'Otentikasi';
$labels['test_connection'] = 'Uji koneksi';
$labels['use_imap_user_pass'] = 'Menggunakan nama pengguna dan kata sandi IMAP';
$labels['specify_user_pass'] = 'Menentukan nama pengguna dan kata sandi';

$labels['validation_required'] = '$f: bidang yang wajib diisi.';
$labels['validation_maxlen'] = '$f: harus lebih pendek dari $n karakter.';
$labels['validation_port'] = '$f harus berupa bilangan bulat dalam rentang 1-65535.';

$labels['login_successful'] = 'Login berhasil.';
$labels['text_in_parentheses'] = '($s)';
$labels['cannot_login_to_imap_server'] = 'Tidak dapat masuk ke server IMAP.';
$labels['cannot_login_to_smtp_server'] = 'Tidak dapat masuk ke server SMTP.';
$labels['cannot_save_multibox_data'] = 'Tidak dapat menyimpan data multibox.';
$labels['settings_not_saved'] = 'Pengaturan tidak disimpan.';
