<?php
/**
 * Roundcube Plus Multibox plugin.
 *
 * Copyright 2023, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['plugin_name'] = 'Multibox';
$labels['app_menu_title'] = 'Pielāgotie pasta serveri';
$labels['custom_email_account'] = 'Pielāgots e-pasta konts';
$labels['use_custom_mail_servers'] = 'Pielāgotu pasta serveru izmantošana';
$labels['incoming_server'] = 'Ienākošais serveris (IMAP)';
$labels['outgoing_server'] = 'izejošais serveris (SMTP)';

$labels['server'] = 'Serveris';
$labels['port'] = 'Osta';
$labels['connection_security'] = 'Savienojuma drošība';
$labels['authentication'] = 'Autentifikācija';
$labels['test_connection'] = 'Testa savienojums';
$labels['use_imap_user_pass'] = 'IMAP lietotājvārda un paroles izmantošana';
$labels['specify_user_pass'] = 'Norādiet lietotājvārdu un paroli';

$labels['validation_required'] = '$f ir nepieciešams.';
$labels['validation_maxlen'] = '$f jābūt īsākam par $n rakstzīmēm.';
$labels['validation_port'] = '$f jābūt veselam skaitlim diapazonā 1-65535.';

$labels['login_successful'] = 'Veiksmīga pieteikšanās.';
$labels['text_in_parentheses'] = '($s)';
$labels['cannot_login_to_imap_server'] = 'Nevar pieteikties IMAP serverī.';
$labels['cannot_login_to_smtp_server'] = 'Nav iespējams pieteikties SMTP serverī.';
$labels['cannot_save_multibox_data'] = 'Nevar saglabāt vairāku lodziņu datus.';
$labels['settings_not_saved'] = 'Iestatījumi nav saglabāti.';
