<?php
/**
 * Roundcube Plus Multibox plugin.
 *
 * Copyright 2023, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['plugin_name'] = 'Multibox';
$labels['app_menu_title'] = 'Tilpassede e-postservere';
$labels['custom_email_account'] = 'Tilpasset e-postkonto';
$labels['use_custom_mail_servers'] = 'Bruk egendefinerte e-postservere';
$labels['incoming_server'] = 'Innkommende server (IMAP)';
$labels['outgoing_server'] = 'Utgående server (SMTP)';

$labels['server'] = 'Server';
$labels['port'] = 'Port';
$labels['connection_security'] = 'Tilkoblingssikkerhet';
$labels['authentication'] = 'Autentisering';
$labels['test_connection'] = 'Test tilkobling';
$labels['use_imap_user_pass'] = 'Bruk IMAP-brukernavn og passord';
$labels['specify_user_pass'] = 'Angi brukernavn og passord';

$labels['validation_required'] = 'f: obligatorisk felt.';
$labels['validation_maxlen'] = '$f: må være kortere enn $n tegn.';
$labels['validation_port'] = '$f må være et heltall i området 1-65535.';

$labels['login_successful'] = 'Innlogging vellykket.';
$labels['text_in_parentheses'] = '($s)';
$labels['cannot_login_to_imap_server'] = 'Kan ikke logge på IMAP-serveren.';
$labels['cannot_login_to_smtp_server'] = 'Kan ikke logge på SMTP-serveren.';
$labels['cannot_save_multibox_data'] = 'Kan ikke lagre multiboksdata.';
$labels['settings_not_saved'] = 'Innstillingene er ikke lagret.';
