<?php
/**
 * Roundcube Plus Multibox plugin.
 *
 * Copyright 2023, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['plugin_name'] = 'Multibox';
$labels['app_menu_title'] = 'Aangepaste mailservers';
$labels['custom_email_account'] = 'Aangepaste e-mailaccount';
$labels['use_custom_mail_servers'] = 'Aangepaste mailservers gebruiken';
$labels['incoming_server'] = 'Inkomende server (IMAP)';
$labels['outgoing_server'] = 'Uitgaande server (SMTP)';

$labels['server'] = 'Server';
$labels['port'] = 'Haven';
$labels['connection_security'] = 'Veiligheid van de verbinding';
$labels['authentication'] = 'Authenticatie';
$labels['test_connection'] = 'Testaansluiting';
$labels['use_imap_user_pass'] = 'Gebruik IMAP-gebruikersnaam en -wachtwoord';
$labels['specify_user_pass'] = 'Gebruikersnaam en wachtwoord opgeven';

$labels['validation_required'] = '$f: verplicht veld.';
$labels['validation_maxlen'] = '$f: moet korter zijn dan $n tekens.';
$labels['validation_port'] = '$f moet een geheel getal zijn in het bereik 1-65535.';

$labels['login_successful'] = 'Inloggen is gelukt.';
$labels['text_in_parentheses'] = '($s)';
$labels['cannot_login_to_imap_server'] = 'Kan niet inloggen op IMAP-server.';
$labels['cannot_login_to_smtp_server'] = 'Kan niet inloggen op SMTP-server.';
$labels['cannot_save_multibox_data'] = 'Kan multiboxgegevens niet opslaan.';
$labels['settings_not_saved'] = 'Instellingen niet opgeslagen.';
