<?php
/**
 * Roundcube Plus Multibox plugin.
 *
 * Copyright 2023, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['plugin_name'] = 'Multibox';
$labels['app_menu_title'] = 'Własne serwery pocztowe';
$labels['custom_email_account'] = 'Własne konto e-mail';
$labels['use_custom_mail_servers'] = 'Użyj własnych serwerów pocztowych';
$labels['incoming_server'] = 'Serwer przychodzący (IMAP)';
$labels['outgoing_server'] = 'Serwer wychodzący (SMTP)';

$labels['server'] = 'Serwer';
$labels['port'] = 'Port';
$labels['connection_security'] = 'Bezpieczeństwo połączeń';
$labels['authentication'] = 'Uwierzytelnianie';
$labels['test_connection'] = 'Połączenie testowe';
$labels['use_imap_user_pass'] = 'Użyj nazwy użytkownika i hasła IMAP';
$labels['specify_user_pass'] = 'Określenie nazwy użytkownika i hasła';

$labels['validation_required'] = '$f: pole wymagane.';
$labels['validation_maxlen'] = '$f: musi być krótsze niż $n znaków.';
$labels['validation_port'] = '$f musi być liczbą całkowitą z zakresu 1-65535.';

$labels['login_successful'] = 'Logowanie zakończone sukcesem.';
$labels['text_in_parentheses'] = '($s)';
$labels['cannot_login_to_imap_server'] = 'Nie można zalogować się do serwera IMAP.';
$labels['cannot_login_to_smtp_server'] = 'Nie można zalogować się do serwera SMTP.';
$labels['cannot_save_multibox_data'] = 'Nie można zapisać danych multibox.';
$labels['settings_not_saved'] = 'Ustawienia nie zostały zapisane.';
