<?php
/**
 * Roundcube Plus Multibox plugin.
 *
 * Copyright 2023, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['plugin_name'] = 'Multibox';
$labels['app_menu_title'] = 'Servidores de correio personalizados';
$labels['custom_email_account'] = 'Conta de correio eletrónico personalizada';
$labels['use_custom_mail_servers'] = 'Utilizar servidores de correio personalizados';
$labels['incoming_server'] = 'Servidor de entrada (IMAP)';
$labels['outgoing_server'] = 'Servidor de saída (SMTP)';

$labels['server'] = 'Servidor';
$labels['port'] = 'Porto';
$labels['connection_security'] = 'Segurança da ligação';
$labels['authentication'] = 'Autenticação';
$labels['test_connection'] = 'Ligação de teste';
$labels['use_imap_user_pass'] = 'Utilizar o nome de utilizador e a palavra-passe IMAP';
$labels['specify_user_pass'] = 'Especificar o nome de utilizador e a palavra-passe';

$labels['validation_required'] = '$f é necessário.';
$labels['validation_maxlen'] = '$f deve ser mais curto do que $n caracteres.';
$labels['validation_port'] = '$f deve ser um número inteiro no intervalo 1-65535.';

$labels['login_successful'] = 'Início de sessão bem sucedido.';
$labels['text_in_parentheses'] = '($s)';
$labels['cannot_login_to_imap_server'] = 'Não é possível iniciar sessão no servidor IMAP.';
$labels['cannot_login_to_smtp_server'] = 'Não é possível iniciar sessão no servidor SMTP.';
$labels['cannot_save_multibox_data'] = 'Não é possível guardar dados de várias caixas.';
$labels['settings_not_saved'] = 'Definições não guardadas.';
