<?php
/**
 * Roundcube Plus Multibox plugin.
 *
 * Copyright 2023, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['plugin_name'] = 'Multibox';
$labels['app_menu_title'] = 'Servere de poștă personalizate';
$labels['custom_email_account'] = 'Cont de e-mail personalizat';
$labels['use_custom_mail_servers'] = 'Utilizați servere de e-mail personalizate';
$labels['incoming_server'] = 'Server de intrare (IMAP)';
$labels['outgoing_server'] = 'Server de ieșire (SMTP)';

$labels['server'] = 'Server';
$labels['port'] = 'Port';
$labels['connection_security'] = 'Securitatea conexiunii';
$labels['authentication'] = 'Autentificare';
$labels['test_connection'] = 'Conexiune de testare';
$labels['use_imap_user_pass'] = 'Utilizați numele de utilizator și parola IMAP';
$labels['specify_user_pass'] = 'Specificați numele de utilizator și parola';

$labels['validation_required'] = '$f: câmp obligatoriu.';
$labels['validation_maxlen'] = '$f: trebuie să fie mai scurt de $n caractere.';
$labels['validation_port'] = '$f trebuie să fie un număr întreg în intervalul 1-65535.';

$labels['login_successful'] = 'Autentificare reușită.';
$labels['text_in_parentheses'] = '($s)';
$labels['cannot_login_to_imap_server'] = 'Nu vă puteți conecta la serverul IMAP.';
$labels['cannot_login_to_smtp_server'] = 'Nu vă puteți conecta la serverul SMTP.';
$labels['cannot_save_multibox_data'] = 'Nu se pot salva datele multibox.';
$labels['settings_not_saved'] = 'Setările nu sunt salvate.';
