<?php
/**
 * Roundcube Plus Multibox plugin.
 *
 * Copyright 2023, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['plugin_name'] = 'Multibox';
$labels['app_menu_title'] = 'Vlastné poštové servery';
$labels['custom_email_account'] = 'Vlastné e-mailové konto';
$labels['use_custom_mail_servers'] = 'Používanie vlastných poštových serverov';
$labels['incoming_server'] = 'Prichádzajúci server (IMAP)';
$labels['outgoing_server'] = 'Odchádzajúci server (SMTP)';

$labels['server'] = 'Server';
$labels['port'] = 'Prístav';
$labels['connection_security'] = 'Zabezpečenie pripojenia';
$labels['authentication'] = 'Overovanie';
$labels['test_connection'] = 'Testovacie pripojenie';
$labels['use_imap_user_pass'] = 'Používanie používateľského mena a hesla IMAP';
$labels['specify_user_pass'] = 'Zadajte používateľské meno a heslo';

$labels['validation_required'] = '$f je povinný.';
$labels['validation_maxlen'] = '$f musí byť kratší ako $n znakov.';
$labels['validation_port'] = '$f musí byť celé číslo v rozsahu 1-65535.';

$labels['login_successful'] = 'Prihlásenie bolo úspešné.';
$labels['text_in_parentheses'] = '($s)';
$labels['cannot_login_to_imap_server'] = 'Nemožno sa prihlásiť na server IMAP.';
$labels['cannot_login_to_smtp_server'] = 'Nemožno sa prihlásiť na server SMTP.';
$labels['cannot_save_multibox_data'] = 'Nie je možné uložiť údaje z viacerých políčok.';
$labels['settings_not_saved'] = 'Nastavenia nie sú uložené.';
