<?php
/**
 * Roundcube Plus Multibox plugin.
 *
 * Copyright 2023, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['plugin_name'] = 'Večpredstavnostna škatla';
$labels['app_menu_title'] = 'Poštni strežniki po meri';
$labels['custom_email_account'] = 'E-poštni račun po meri';
$labels['use_custom_mail_servers'] = 'Uporaba poštnih strežnikov po meri';
$labels['incoming_server'] = 'Dohodni strežnik (IMAP)';
$labels['outgoing_server'] = 'Odhodni strežnik (SMTP)';

$labels['server'] = 'Strežnik';
$labels['port'] = 'Pristanišče';
$labels['connection_security'] = 'Varnost povezave';
$labels['authentication'] = 'Preverjanje pristnosti';
$labels['test_connection'] = 'Preizkusna povezava';
$labels['use_imap_user_pass'] = 'Uporaba uporabniškega imena in gesla IMAP';
$labels['specify_user_pass'] = 'Določite uporabniško ime in geslo';

$labels['validation_required'] = '$f: obvezno polje.';
$labels['validation_maxlen'] = '$f: mora biti krajši od $n znakov.';
$labels['validation_port'] = '$f mora biti celo število v območju 1-65535.';

$labels['login_successful'] = 'Prijava je bila uspešna.';
$labels['text_in_parentheses'] = '($s)';
$labels['cannot_login_to_imap_server'] = 'Ne morete se prijaviti v strežnik IMAP.';
$labels['cannot_login_to_smtp_server'] = 'Ne morete se prijaviti v strežnik SMTP.';
$labels['cannot_save_multibox_data'] = 'Ni mogoče shraniti podatkov iz več okenc.';
$labels['settings_not_saved'] = 'Nastavitve niso shranjene.';
