<?php
/**
 * Roundcube Plus Multibox plugin.
 *
 * Copyright 2023, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['plugin_name'] = 'Multibox';
$labels['app_menu_title'] = 'Anpassade e-postservrar';
$labels['custom_email_account'] = 'Anpassat e-postkonto';
$labels['use_custom_mail_servers'] = 'Använd egna e-postservrar';
$labels['incoming_server'] = 'Server för inkommande meddelanden (IMAP)';
$labels['outgoing_server'] = 'Utgående server (SMTP)';

$labels['server'] = 'Server';
$labels['port'] = 'Port';
$labels['connection_security'] = 'Anslutningssäkerhet';
$labels['authentication'] = 'Autentisering';
$labels['test_connection'] = 'Testanslutning';
$labels['use_imap_user_pass'] = 'Använd användarnamn och lösenord för IMAP';
$labels['specify_user_pass'] = 'Ange användarnamn och lösenord';

$labels['validation_required'] = '$f krävs.';
$labels['validation_maxlen'] = '$f måste vara kortare än $n tecken.';
$labels['validation_port'] = '$f måste vara ett heltal inom intervallet 1-65535.';

$labels['login_successful'] = 'Inloggningen lyckades.';
$labels['text_in_parentheses'] = '($s)';
$labels['cannot_login_to_imap_server'] = 'Det går inte att logga in på IMAP-servern.';
$labels['cannot_login_to_smtp_server'] = 'Det går inte att logga in på SMTP-servern.';
$labels['cannot_save_multibox_data'] = 'Det går inte att spara multibox-data.';
$labels['settings_not_saved'] = 'Inställningarna sparas inte.';
