<?php
/**
 * Roundcube Plus Multibox plugin.
 *
 * Copyright 2023, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['plugin_name'] = 'Мультибокс';
$labels['app_menu_title'] = 'Користувацькі поштові сервери';
$labels['custom_email_account'] = 'Власний обліковий запис електронної пошти';
$labels['use_custom_mail_servers'] = 'Використовуйте власні поштові сервери';
$labels['incoming_server'] = 'Вхідний сервер (IMAP)';
$labels['outgoing_server'] = 'Вихідний сервер (SMTP)';

$labels['server'] = 'Сервер';
$labels['port'] = 'Порт';
$labels['connection_security'] = 'Безпека з\'єднання';
$labels['authentication'] = 'Аутентифікація';
$labels['test_connection'] = 'Тестове підключення';
$labels['use_imap_user_pass'] = 'Використовуйте ім\'я користувача та пароль IMAP';
$labels['specify_user_pass'] = 'Вкажіть ім\'я користувача та пароль';

$labels['validation_required'] = 'Потрібно ввести $f.';
$labels['validation_maxlen'] = '$f має бути коротшим за $n символів.';
$labels['validation_port'] = '$f має бути цілим числом у діапазоні 1-65535.';

$labels['login_successful'] = 'Успішний вхід.';
$labels['text_in_parentheses'] = '($s)';
$labels['cannot_login_to_imap_server'] = 'Не вдається увійти на сервер IMAP.';
$labels['cannot_login_to_smtp_server'] = 'Не вдається увійти на SMTP-сервер.';
$labels['cannot_save_multibox_data'] = 'Не вдається зберегти дані з декількох полів.';
$labels['settings_not_saved'] = 'Налаштування не збережено.';
