<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Опции на интерфейса';
$labels['disable_mobile_skin'] = 'Използване на кожата на работния плот';
$labels['enable_mobile_skin'] = 'Използване на мобилна кожа';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Вид и усещане на кожата';
$labels['skin_look_and_feel'] = 'Вид и усещане на кожата';
$labels['icons'] = 'Икони';
$labels['icons_solid'] = 'Solid';
$labels['icons_traditional'] = 'Традиционен';
$labels['icons_outlined'] = 'Очертан';
$labels['icons_material'] = 'Материал';
$labels['icons_cartoon'] = 'Карикатура';
$labels['setting_list_icons'] = 'Икони в списъци';
$labels['setting_button_icons'] = 'Икони върху бутоните';
$labels['setting_font_size'] = 'Размер на шрифта';
$labels['font_size_xs'] = 'Най-малкият';
$labels['font_size_s'] = 'По-малко';
$labels['font_size_n'] = 'Нормален';
$labels['font_size_l'] = 'По-голям';
$labels['font_size_xl'] = 'Най-големият';
$labels['setting_thick_font'] = 'Дебел шрифт';
$labels['setting_font_family'] = 'Семейство шрифтове';
$labels['setting_color'] = 'Цвят';
$labels['save_hint'] = 'Не забравяйте да запазите настройките си, като кликнете върху бутона "Запази" по-долу.';

