<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Opciones de interfaz';
$labels['disable_mobile_skin'] = 'Usar skin de escritorio';
$labels['enable_mobile_skin'] = 'Utilizar la piel móvil';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Aspecto y tacto de la piel';
$labels['skin_look_and_feel'] = 'Aspecto y tacto de la piel';
$labels['icons'] = 'Iconos';
$labels['icons_solid'] = 'Sólido';
$labels['icons_traditional'] = 'Tradicional';
$labels['icons_outlined'] = 'Esbozado';
$labels['icons_material'] = 'Material';
$labels['icons_cartoon'] = 'Dibujos animados';
$labels['setting_list_icons'] = 'Iconos en las listas';
$labels['setting_button_icons'] = 'Iconos en los botones';
$labels['setting_font_size'] = 'Tamaño de letra';
$labels['font_size_xs'] = 'El más pequeño';
$labels['font_size_s'] = 'Más pequeño';
$labels['font_size_n'] = 'Normal';
$labels['font_size_l'] = 'Más grande';
$labels['font_size_xl'] = 'Mayor';
$labels['setting_thick_font'] = 'Fuente gruesa';
$labels['setting_font_family'] = 'Familia de fuentes';
$labels['setting_color'] = 'Color';
$labels['save_hint'] = 'No olvides guardar la configuración haciendo clic en el botón "Guardar".';

