<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Liidesevõimalused';
$labels['disable_mobile_skin'] = 'Kasutage töölaua nahka';
$labels['enable_mobile_skin'] = 'Kasutage mobiiltelefoni nahka';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Naha välimus ja tunne';
$labels['skin_look_and_feel'] = 'Naha välimus ja tunne';
$labels['icons'] = 'Ikoonid';
$labels['icons_solid'] = 'Soliidne';
$labels['icons_traditional'] = 'Traditsiooniline';
$labels['icons_outlined'] = 'Välja toodud';
$labels['icons_material'] = 'Materjal';
$labels['icons_cartoon'] = 'Cartoon';
$labels['setting_list_icons'] = 'Ikoonid nimekirjades';
$labels['setting_button_icons'] = 'Ikoonid nuppudel';
$labels['setting_font_size'] = 'Kirjasuurus';
$labels['font_size_xs'] = 'Väikseim';
$labels['font_size_s'] = 'Väiksemad';
$labels['font_size_n'] = 'Tavaline';
$labels['font_size_l'] = 'Suurem';
$labels['font_size_xl'] = 'Suurim';
$labels['setting_thick_font'] = 'Paks kirjatüüp';
$labels['setting_font_family'] = 'Kirjatüüpkond';
$labels['setting_color'] = 'Värv';
$labels['save_hint'] = 'Ärge unustage oma seaded salvestada, klõpsates alloleval nupul "Salvesta".';

