<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Opțiuni de interfață';
$labels['disable_mobile_skin'] = 'Utilizați skin-ul pentru desktop';
$labels['enable_mobile_skin'] = 'Utilizați pielea mobilă';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Aspectul și senzația pielii';
$labels['skin_look_and_feel'] = 'Aspectul și senzația pielii';
$labels['icons'] = 'Icoane';
$labels['icons_solid'] = 'Solid';
$labels['icons_traditional'] = 'Tradițional';
$labels['icons_outlined'] = 'Schițat';
$labels['icons_material'] = 'Material';
$labels['icons_cartoon'] = 'Desen animat';
$labels['setting_list_icons'] = 'Icoane în liste';
$labels['setting_button_icons'] = 'Pictograme pe butoane';
$labels['setting_font_size'] = 'Mărimea fontului';
$labels['font_size_xs'] = 'Cel mai mic';
$labels['font_size_s'] = 'Mai mici';
$labels['font_size_n'] = 'Normal';
$labels['font_size_l'] = 'Mai mare';
$labels['font_size_xl'] = 'Cel mai mare';
$labels['setting_thick_font'] = 'Font gros';
$labels['setting_font_family'] = 'Familie de fonturi';
$labels['setting_color'] = 'Culoare';
$labels['save_hint'] = 'Nu uitați să vă salvați setările făcând clic pe butonul "Save" de mai jos.';

