<?php
/**
 * Roundcube Plus Skin plugin.
 *
 * Copyright 2019, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

// larry based

$labels['interface_options'] = 'Alternativ för gränssnitt';
$labels['disable_mobile_skin'] = 'Använd desktop skin';
$labels['enable_mobile_skin'] = 'Använd mobil hud';

// elastic based

$labels['skin_look_and_feel_shortcut'] = 'Hudens utseende och känsla';
$labels['skin_look_and_feel'] = 'Hudens utseende och känsla';
$labels['icons'] = 'Ikoner';
$labels['icons_solid'] = 'Solid';
$labels['icons_traditional'] = 'Traditionell';
$labels['icons_outlined'] = 'Beskrivet';
$labels['icons_material'] = 'Material';
$labels['icons_cartoon'] = 'Tecknad film';
$labels['setting_list_icons'] = 'Ikoner i listor';
$labels['setting_button_icons'] = 'Ikoner på knappar';
$labels['setting_font_size'] = 'Fontstorlek';
$labels['font_size_xs'] = 'Den minsta';
$labels['font_size_s'] = 'Mindre';
$labels['font_size_n'] = 'Normal';
$labels['font_size_l'] = 'Större';
$labels['font_size_xl'] = 'Störst';
$labels['setting_thick_font'] = 'Tjockt typsnitt';
$labels['setting_font_family'] = 'Fontfamilj';
$labels['setting_color'] = 'Färg';
$labels['save_hint'] = 'Glöm inte att spara dina inställningar genom att klicka på knappen "Spara" nedan.';

