<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Диск на Google';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Вмъкване на връзка към съобщението';
$labels['download_and_attach'] = 'Изтегляне и прикачване';
$labels['sidebar'] = 'Странична лента';
$labels['sidebar_items'] = 'Елементи от страничната лента';
$labels['sidebar_change_order'] = 'Плъзнете и пуснете елементите от страничната лента, за да промените реда им.';
$labels['preview'] = 'Преглед';
$labels['apps'] = 'Приложения';
$labels['sidebar'] = 'Странична лента';
$labels['hide'] = 'Скрий';
$labels['invalid_image_extension'] = 'Неправилно разширение на файла с изображението. Разрешените разширения са: $ext.';
$labels['invalid_image_format'] = 'Този файл не е валидно изображение.';
$labels['copy_to_clipboard'] = 'Копиране в клипборда';
$labels['copied_to_clipboard'] = 'Копирано в клипборда.';
$labels['cannot_copy_to_clipboard'] = 'Не мога да копирам текст в клипборда.';
