<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drev';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Indsæt link til meddelelsen';
$labels['download_and_attach'] = 'Download og vedhæftes';
$labels['sidebar'] = 'Sidebar';
$labels['sidebar_items'] = 'Elementer i sidebaren';
$labels['sidebar_change_order'] = 'Træk og slip elementer i sidebaren for at ændre deres rækkefølge.';
$labels['preview'] = 'Forhåndsvisning';
$labels['apps'] = 'Apps';
$labels['sidebar'] = 'Sidebar';
$labels['hide'] = 'Skjul';
$labels['invalid_image_extension'] = 'Ugyldig billedfiludvidelse. De tilladte udvidelser er: $ext.';
$labels['invalid_image_format'] = 'Denne fil er ikke et gyldigt billede.';
$labels['copy_to_clipboard'] = 'Kopier til udklipsholder';
$labels['copied_to_clipboard'] = 'Kopieret til udklipsholderen.';
$labels['cannot_copy_to_clipboard'] = 'Kan ikke kopiere tekst til udklipsholderen.';
