<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Inserir link para a mensagem';
$labels['download_and_attach'] = 'Baixar e anexar';
$labels['sidebar'] = 'Sidebar';
$labels['sidebar_items'] = 'Artigos de barra lateral';
$labels['sidebar_change_order'] = 'Arraste e solte os itens da barra lateral para alterar seu pedido.';
$labels['preview'] = 'Pré-visualização';
$labels['apps'] = 'Apps';
$labels['sidebar'] = 'Sidebar';
$labels['hide'] = 'Esconder';
$labels['invalid_image_extension'] = 'Extensão inválida do arquivo de imagem. As extensões permitidas são: Extensão de $ext.';
$labels['invalid_image_format'] = 'Este arquivo não é uma imagem válida.';
$labels['copy_to_clipboard'] = 'Copiar para a área de transferência';
$labels['copied_to_clipboard'] = 'Copiado para a área de transferência.';
$labels['cannot_copy_to_clipboard'] = 'Não é possível copiar texto para a área de transferência.';
