<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Вставить ссылку в сообщение';
$labels['download_and_attach'] = 'загрузить и прикрепить';
$labels['sidebar'] = 'Боковая панель';
$labels['sidebar_items'] = 'Элементы боковой панели';
$labels['sidebar_change_order'] = 'Перетащите элементы боковой панели, чтобы изменить их порядок.';
$labels['preview'] = 'Предварительный просмотр';
$labels['apps'] = 'Приложения';
$labels['sidebar'] = 'Боковая панель';
$labels['hide'] = 'Спрятать';
$labels['invalid_image_extension'] = 'Неверное расширение изображения. Допустимые расширения: $ext.';
$labels['invalid_image_format'] = 'Этот файл не является действительным изображением.';
$labels['copy_to_clipboard'] = 'Копировать в буфер обмена';
$labels['copied_to_clipboard'] = 'Скопировано в буфер обмена.';
$labels['cannot_copy_to_clipboard'] = 'Невозможно скопировать текст в буфер обмена.';
