<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Disk Google';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Vložiť odkaz na správu';
$labels['download_and_attach'] = 'Stiahnite si a pripojte';
$labels['sidebar'] = 'Bočný panel';
$labels['sidebar_items'] = 'Položky bočného panela';
$labels['sidebar_change_order'] = 'Ťahaním a púšťaním položiek bočného panela môžete zmeniť ich poradie.';
$labels['preview'] = 'Náhľad';
$labels['apps'] = 'Aplikácie';
$labels['sidebar'] = 'Bočný panel';
$labels['hide'] = 'Skryť';
$labels['invalid_image_extension'] = 'Nesprávna prípona súboru obrázka. Povolené prípony sú: $ext.';
$labels['invalid_image_format'] = 'Tento súbor nie je platný obrázok.';
$labels['copy_to_clipboard'] = 'Kopírovanie do schránky';
$labels['copied_to_clipboard'] = 'Skopírované do schránky.';
$labels['cannot_copy_to_clipboard'] = 'Nie je možné skopírovať text do schránky.';
