<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'WebDAV';
$labels['insert_link'] = 'Vstavite povezavo do sporočila';
$labels['download_and_attach'] = 'Prenesite in priložite';
$labels['sidebar'] = 'Stranska vrstica';
$labels['sidebar_items'] = 'Elementi stranske vrstice';
$labels['sidebar_change_order'] = 'Povlecite in spustite elemente stranske vrstice, da spremenite njihov vrstni red.';
$labels['preview'] = 'Predogled';
$labels['apps'] = 'Aplikacije';
$labels['sidebar'] = 'Stranska vrstica';
$labels['hide'] = 'Skrij';
$labels['invalid_image_extension'] = 'Nepravilna razširitev slikovne datoteke. Dovoljene razširitve so: $ext.';
$labels['invalid_image_format'] = 'Ta datoteka ni veljavna slika.';
$labels['copy_to_clipboard'] = 'Kopiranje v odložišče';
$labels['copied_to_clipboard'] = 'Kopiranje v odložišče.';
$labels['cannot_copy_to_clipboard'] = 'Besedila ni mogoče kopirati v odložišče.';
