<?php

$labels = [];
$labels['draft'] = 'Entwurf';
$labels['draft_in_thread'] = 'Diese Unterhaltung enthält einen aktiven Entwurf';
$labels['draft_notice'] = 'Sie haben einen aktiven Entwurf für diese Nachricht';
$labels['resume_draft'] = 'Entwurf fortsetzen';
$labels['reply'] = 'Gesendet';
$labels['replied_in_thread'] = 'Diese Konversation enthält gesendete Antworten';
$labels['thread_drafts'] = 'Entwürfe & Antworten in Themen';
$labels['thread_drafts_option'] = 'Aktive Entwürfe in Konversationsthemen einbinden';
$labels['thread_replies_option'] = 'Gesendete Antworten in Konversationen anzeigen';
$labels['thread_drafts_banner_option'] = 'Entwurfshinweis beim Anzeigen von Nachrichten mit Entwurfsantworten einblenden';
$labels['to'] = 'An';
