<?php

$labels = [];
$labels['draft'] = 'Draft';
$labels['draft_in_thread'] = 'This conversation contains an active draft';
$labels['draft_notice'] = 'You have an active draft reply for this message';
$labels['resume_draft'] = 'Resume Draft';
$labels['reply'] = 'Sent';
$labels['replied_in_thread'] = 'This conversation contains sent replies';
$labels['thread_drafts'] = 'Thread Drafts & Replies';
$labels['thread_drafts_option'] = 'Include active drafts in conversation threads';
$labels['thread_replies_option'] = 'Include sent replies in conversation threads';
$labels['thread_drafts_banner_option'] = 'Show draft notice when viewing messages with draft replies';
$labels['to'] = 'To';
