<?php

$labels = [];
$labels['draft'] = 'Brouillon';
$labels['draft_in_thread'] = 'Cette conversation contient un brouillon actif';
$labels['draft_notice'] = 'Vous avez un brouillon de réponse actif pour ce message';
$labels['resume_draft'] = 'Reprendre le brouillon';
$labels['reply'] = 'Envoyé';
$labels['replied_in_thread'] = 'Cette conversation contient des réponses envoyées';
$labels['thread_drafts'] = 'Brouillons et réponses dans les fils';
$labels['thread_drafts_option'] = 'Inclure les brouillons actifs dans les fils de discussion';
$labels['thread_replies_option'] = 'Inclure les réponses envoyées dans les fils de discussion';
$labels['thread_drafts_banner_option'] = 'Afficher une notification lors de la lecture d\'un message avec réponse en brouillon';
$labels['to'] = 'À';
