<?php

$labels = [];
$labels['draft'] = 'Concept';
$labels['draft_in_thread'] = 'Dit gesprek bevat een actief concept';
$labels['draft_notice'] = 'U heeft een actief conceptantwoord voor dit bericht';
$labels['resume_draft'] = 'Concept bewerken';
$labels['thread_drafts'] = 'Concepten in discussies';
$labels['thread_drafts_option'] = 'Actieve concepten opnemen in discussielijnen';
$labels['thread_drafts_banner_option'] = 'Toon conceptmelding bij het bekijken van berichten met conceptantwoorden';
