<?php

/**
 * ManageSieve Rule Exporter & Synchronizer
 *
 * Generates RFC 5230 compliant Sieve vacation and redirect scripts
 * based on the user's active preferences and templates.
 *
 * @license MIT
 * @author Webdotpulse & LifePrisma Contributors
 */

declare(strict_types=1);

require_once __DIR__ . '/TemplateManager.php';

class VacationForwardSieveSync
{
    /**
     * Generate complete Sieve script.
     */
    public static function generateScript(array $prefs, array $identity): string
    {
        $requires = ['vacation', 'copy'];
        $hasSchedule = ($prefs['vacation_status'] ?? '') === 'scheduled';
        if ($hasSchedule) {
            $requires[] = 'date';
            $requires[] = 'relational';
        }

        $lines = [];
        $lines[] = '# ============================================================';
        $lines[] = '# Sieve filter generated by Roundcube Vacation & Forwarding';
        $lines[] = '# Generated at: ' . date('Y-m-d H:i:s');
        $lines[] = '# ============================================================';
        $lines[] = '';
        $lines[] = 'require ["' . implode('", "', array_unique($requires)) . '"];';
        $lines[] = '';

        // Forwarding section
        $forwardStatus = $prefs['forward_status'] ?? 'disabled';
        $destinations = VacationForwardForwardEngine::parseDestinations($prefs['forward_destinations'] ?? '');
        $keepCopy = !empty($prefs['forward_keep_copy']);

        if ($forwardStatus !== 'disabled' && !empty($destinations)) {
            $lines[] = '# --- Mail Forwarding Rules ---';
            foreach ($destinations as $dest) {
                if ($keepCopy) {
                    $lines[] = 'redirect :copy "' . addcslashes($dest, '"\\') . '";';
                } else {
                    $lines[] = 'redirect "' . addcslashes($dest, '"\\') . '";';
                }
            }
            $lines[] = '';
        }

        // Vacation section
        $vacationStatus = $prefs['vacation_status'] ?? 'disabled';
        if ($vacationStatus !== 'disabled') {
            $days = match ($prefs['vacation_rate_interval'] ?? '1_day') {
                '1_hour', '6_hours', '12_hours', '1_day' => 1,
                '2_days' => 2,
                '3_days' => 3,
                '7_days' => 7,
                '14_days' => 14,
                default => 1,
            };

            $templates = $prefs['vacation_templates'] ?? [];
            if (empty($templates)) {
                $templates = VacationForwardTemplateManager::getDefaultTemplates();
            }

            // Find default template
            $chosenTemplate = $templates[0];
            foreach ($templates as $t) {
                if (!empty($t['is_default'])) {
                    $chosenTemplate = $t;
                    break;
                }
            }

            $userEmail = $identity['email'] ?? 'webmail@localhost';
            $userName = $identity['name'] ?? 'User';
            $startDate = !empty($prefs['vacation_start']) ? date('Y-m-d', strtotime($prefs['vacation_start'])) : '';
            $endDate = !empty($prefs['vacation_end']) ? date('Y-m-d', strtotime($prefs['vacation_end'])) : '';
            $returnDate = VacationForwardTemplateManager::calculateReturnDate($prefs['vacation_end'] ?? null);

            $context = [
                'start_date' => $startDate,
                'end_date' => $endDate,
                'return_date' => $returnDate,
                'sender_name' => 'Colleague',
                'sender_email' => 'colleague@example.com',
                'original_subject' => '${subject}',
                'user_name' => $userName,
                'user_email' => $userEmail,
            ];

            $subject = VacationForwardTemplateManager::interpolate($chosenTemplate['subject'] ?? 'Out of Office', $context);
            $body = VacationForwardTemplateManager::interpolate($chosenTemplate['body'] ?? 'I am away.', $context);

            $lines[] = '# --- Vacation Auto-Reply Rule ---';
            if ($hasSchedule && $startDate !== '' && $endDate !== '') {
                $lines[] = "if allof (currentdate :value \"ge\" \"date\" \"{$startDate}\",";
                $lines[] = "          currentdate :value \"le\" \"date\" \"{$endDate}\") {";
                $indent = '    ';
            } else {
                $indent = '';
            }

            $lines[] = $indent . 'vacation';
            $lines[] = $indent . '    :days ' . $days;
            $lines[] = $indent . '    :subject "' . addcslashes($subject, '"\\') . '"';
            $lines[] = $indent . '    :addresses ["' . addcslashes($userEmail, '"\\') . '"]';
            $lines[] = $indent . 'text:';

            $bodyLines = explode("\n", $body);
            foreach ($bodyLines as $bl) {
                $lines[] = $indent . rtrim($bl);
            }
            $lines[] = '.';
            $lines[] = ';';

            if ($hasSchedule && $startDate !== '' && $endDate !== '') {
                $lines[] = '}';
            }
            $lines[] = '';
        }

        return implode("\n", $lines) . "\n";
    }
}
